### ISSUE TITLE
ksy file with beginning BOM character fails to compile using kaitai-struct-compiler

### ISSUE THREAD

**Issue by bibekdw** [kaitai-io/kaitai_struct#499] opened 2018-12-17 16:30 UTC
Kaitai-struct-compiler throws error "/∩╗┐meta: unknown key found, expected: doc, doc-ref, enums, instances, meta, params, seq, types" for the ksy file if it has BOM char at the beginning (UTF-8 BOM). As a work around I manually changed the file encoding to UTF-8 and it works.

OS - windows 7 Professional
kaitai-struct-compiler 0.8
JDK 10

**Comment by GreyCat** [comment] 2018-12-17 17:05
It turns out that our usage of `FileReader` for opening YAML files in Java triggers use of system locale. If it's UTF-8, Java can handle (=skip) BOM properly (NB: don't trust [this](https://stackoverflow.com/a/4897993/487064)), but if locale is not Unicode-aware (and on Windows, it seems to be always something non-UTF8), this leads to this problem.

On Linux/Mac, a simple way to reproduce this is to run ksc as `LC_ALL=C ksc ...`, which typically leads to:

```
/???meta: unknown key found, expected: doc, doc-ref, enums, instances, meta, params, seq, types
```

A fix to always force use of UTF8 stream is incoming.

**Comment by GreyCat** [comment] 2018-12-17 20:02
Should be fixed with https://github.com/kaitai-io/kaitai_struct_compiler/commit/42cb8e40e729f422a636eb77200d389f4535d8c4.

**Comment by GreyCat** [comment] 2018-12-27 18:19
No reply for 10 days, works for me => closing. Please feel free to reopen if you still observe the problem.

**Closed by GreyCat** 2018-12-27 18:19 UTC
Labels: bug found
