### ISSUE TITLE
Generated Javascript assumes KaitaiStream globally available

### ISSUE THREAD

**Issue by raymond-h** [kaitai-io/kaitai_struct#180] opened 2017-06-02 01:25 UTC
Generated Javascript will currently gladly refer to `KaitaiStream` without ever trying to import it explicitly. This happens to work only because the runtime also happens to attach `KaitaiStream` to the global scope.

Instead the runtime should not expose it globally the way it currently does, and the generated code should always import the runtime explicitly.

**Comment by GreyCat** [comment] 2017-06-02 05:44
I guess there should be an option for that? At least people using runtime in browsers don't always want to use an intricate build process to replace that `require` call, or is there a way to stay compatible everywhere?

**Comment by raymond-h** [comment] 2017-06-02 06:45
UMD lets you fall back to using global scope if neither an AMD or CommonJS environment is detected. AFAIK that should cover pretty much all cases actually (including runtime as script tag, Browserify & webpack, NodeJS, etc...).

The runtime already does something very close to that already, but it always attaches to global scope as well, and the generated code always relies on the runtime being available globally.

**Comment by GreyCat** [comment] 2017-06-02 07:15
Patches are welcome then, I'm probably not that proficient in JavaScript :)

**Comment by raymond-h** [comment] 2017-07-01 22:20
I started work on this issue, and now that kaitai-io/kaitai_struct_javascript_runtime#2 has been resolved I can make a PR to fix this issue in the near future probably.

**Comment by GreyCat** [comment] 2017-07-03 17:31
@koczkatamas Note that @raymond-h already started work on adapting the compiler to use UMD module standard: https://github.com/raymond-h/kaitai_struct_compiler

**Comment by KOLANICH** [comment] 2017-07-04 23:45
According to [MDN](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/import) ECMAScript modules have landed to most of browsers though they are behind a pref. Do we really need UMD and all these surrogates?

**Comment by koczkatamas** [comment] 2017-07-05 00:30
We are preparing for integrating with older systems which does not and won't support ES modules sadly.

**Comment by KOLANICH** [comment] 2017-07-05 08:52
I have a Pentium 3-based pc. Latest Firefox works (not very fine because of lack of memory) on it.

**Comment by koczkatamas** [comment] 2017-07-05 08:59
I was thinking about enterprise software running in IE or old Node versions.

WebIDE tries to keep compatibility with the latest Firefox ESR version.

Currently ES modules are behind flags even in latest browsers.

We can reiterate this later if the situation changes.

**Comment by KOLANICH** [comment] 2017-07-06 06:21
>I was thinking about enterprise software running in IE or old Node versions.

[ActiveX-capable IE doesn't have typed arrays.](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array)

There is no reason to use ActiveX-non-capable IE (except certification) instead of modern browsers.

>Currently ES modules are behind flags even in latest browsers.

Why not to instruct the users to enable them?

**Comment by koczkatamas** [comment] 2017-07-06 07:54
> Why not to instruct the users to enable them?

So for just to make our job a little easier ask every one of the Kaitai users to enable an experimental, maybe dangerous feature in their browser?

That would be slightly unprofessional, so nope, that won't happen :)

**Comment by koczkatamas** [comment] 2017-07-06 08:22
But actually we could create a command line parameter for the compiler which decides whether we generate UMD or ES module code. And we could bundle both for npm.

**Comment by koczkatamas** [comment] 2017-08-09 19:15
Here is my proposal how to generate UMD modules: [umd_test.zip](https://github.com/kaitai-io/kaitai_struct/files/1212597/umd_test.zip)

There are 3 examples in the ZIP:
 - `index.js`: node example (node index.js)
 - `index.html`: browser example using script tags
 - `index_require.html`: browser example using AMD loader (require.js)

To be able run the browser ones you may need to use a HTTP server (file:// protocol does not work). Easiest way to create one by running `python -mSimpleHTTPServer`.

I also put the originally generated JS files to make comparison easier, they are flagged with `.orig` in their filenames.

The call chain I am using is `Jpeg -> Exif -> ExifBe, ExifLe`.

Here is the difference between the after and before state of the generated `Jpeg` code:

![after-before](https://user-images.githubusercontent.com/2608082/29139388-080f56f8-7d47-11e7-847c-30c94dfd441c.png)

**Comment by GreyCat** [comment] 2017-08-09 19:16
Thanks! I'll try to implement it soon.

**Comment by GreyCat** [comment] 2017-09-05 17:22
Looks like we've finally made it. Off to CI it goes. As a bonus feature, imports should now work more or less flawlessly with JS, which, in turn, would make it possible to do #51 for JS.

**Comment by GreyCat** [comment] 2017-09-06 17:57
@koczkatamas confirmed that it integrates OK into the web IDE, all the tests pass, so I'm marking this as "closed". I've confirmed that [devel IDE](http://ide.kaitai.io/devel/) indeed works with these new UMD-compliant files. Feel free to reopen if anyone has any more concerns.

**Closed by GreyCat** 2017-09-06 17:57 UTC
Labels: enhancement

**Comment by KOLANICH** [comment] 2018-05-02 16:54
https://developer.mozilla.org/en-US/Firefox/Releases/60
>ECMAScript 6 module support is implemented and enabled across all platforms ([bug 568953](https://bugzilla.mozilla.org/show_bug.cgi?id=568953)).

**Comment by connor4312** [comment] 2022-01-08 04:44
You can also add a `module` field in your package.json which points to the es module version of the code. This can allow you to publish it without requiring a breaking change.
