### ISSUE TITLE
Why not C? - C can be access by any language and run on any platform

### ISSUE THREAD

**Issue by SamuelMarks** [kaitai-io/kaitai_struct#1078] opened 2023-12-05 23:49 UTC
From my understanding, the disadvantages would be requirement of distributing precompiled [shared libraries](https://en.wikipedia.org/wiki/Shared_library) (so the host system could work without [build tools](https://en.wikipedia.org/wiki/Software_build#Build_tools); assuming [tcc](http://savannah.nongnu.org/projects/tinycc) or [αpε](https://justine.lol/ape.html) is not used instead). Other disadvantages would be the lack of [namespaces](https://en.wikipedia.org/wiki/Namespace#C++), and types not being as complete as they are in other languages like [FORTRAN](https://en.wikipedia.org/wiki/Fortran) and [ASN.1](https://en.wikipedia.org/wiki/ASN.1).

But it would be far more portable to target [C](https://en.wikipedia.org/wiki/C_(programming_language)) than any other language, right?

(yes yes I know some of the languages that can be targeted with Kaitai [[Nim](https://nim-lang.org)] can produce C code;)

So maybe it's more of a future request, extending the Nim target to create:

  0. wrappable C libraries
  1. [FFI](https://en.wikipedia.org/wiki/Foreign_function_interface) access code (generated automatically) in dozens of programming languages
  2. release these to their respective app stores (`pip install`, `cargo install`, &etc.)

Thoughts?

**Comment by generalmimon** [comment] 2023-12-05 23:52
Please join the discussion in https://github.com/kaitai-io/kaitai_struct/issues/263.

**Comment by generalmimon** [comment] 2023-12-05 23:53
Duplicate of #263

**Closed by generalmimon** 2023-12-05 23:53 UTC
Labels: new language support, duplicate

**Comment by SamuelMarks** [comment] 2023-12-05 23:57
Thanks. Missed that. Commented on that issue.
