### ISSUE TITLE
[compiler] --python-package is not applied to relative imports / imported file is compiled into wrong directory

### ISSUE THREAD

**Issue by smarek** [kaitai-io/kaitai_struct#915] opened 2021-11-05 20:27 UTC
**Showcase:**
This branch https://github.com/OK-DMR/dmr-kaitai/tree/kaitai-relative-imports-not-working
and this commit specifically https://github.com/OK-DMR/dmr-kaitai/commit/21a89704681182aad2a65dc00e4385da3662759a#

*Commit shows the result of adding relative import to existing .ksy and result in compiled .py files*

**Issue**:
  1. Missing `from okdmr.kaitai.hytera.link_control import LinkControl` from resulting `mmdvm2020.py`
  2. Imported file is compiled in current directory (but that is currently probably un-avoidable until #914 is addressed)

**Testing/Reproducing**:
  1. Change .ksy file
  2. Run `rebuild-all.sh` from root of the repository
  3. Observe in `git diff`

**What should happen instead**
  1. When resolving relative imports resulting package of imported file should be based on `--python-package` from original compiler command, which would result in correct import statement of imported
  2. Ideally the imported file would be compiled under relative directory, equal to `meta/imports`, and not in current directory  (in commit you can see the freshly created okdmr/kaitai/homebrew/link_control.py which should not even be there), and import should be correctly `from okdmr.kaitai.etsi.link_control import LinkControl` (even if existence of this package and file should be just assumed)

**Comment by dgelessus** [comment] 2021-11-05 21:42
> 1. Missing `from okdmr.kaitai.hytera.link_control import LinkControl` from resulting `mmdvm2020.py`

This is a known issue, and it's not related to relative imports or packages. It happens when a spec is imported and used for its nested types/enums, but its top-level type is not referenced. See #876.

> 2. Imported file is compiled in current directory

This is currently the expected behavior, sorry. At the moment, the compiler "flattens" the directory structure of the input .ksy files - all generated modules are written into a single directory, and the generated code expects this flat structure. `--python-package` lets you change the name of the package where the modules are placed, but you have to use the same package for all .ksy files that reference each other.

To clarify, re. the issue title - the compiler is not "copying" anything here. When you compile a .ksy file, the compiler looks up all .ksy files that are referenced in `imports` and recursively compiles them as well. All files are compiled using the same compiler settings, regardless of whether they are explicitly listed on the command line or referenced via `imports`. In your case, when you're compiling the directory `okdmr/kaitai/homebrew`, you call the compiler with `--python-package=okdmr.kaitai.homebrew` - and that package name applies to imported .ksy files as well, so they are compiled into the same package as your main .ksy files.

As you've pointed out, this will need to be changed when the compiler gains proper support for namespaces/packages, and I think these two issues have to be handled together. It's not really possible to solve this issue separately from the larger task of supporting packages in the compiler, because if the compiler doesn't know anything about a package structure, it doesn't have the necessary information to generate cross-package imports.

**Comment by smarek** [comment] 2021-11-05 22:02
@dgelessus thank you, i've just reworded the title

ad 1)
  - this was really not clear to me, that it's not "compiler puts the resulting python file into incorrect directory" but "compiler uses the same params for imported files as well"
  - regardless of the reason, the import is missing, even if the resulting parser is in wrong directory, **once there is --python-package all imports must be referenced**, sincerely this would not be an issue if intent was to get both *importing* and *imported* into same result package (which sometimes might be the case)

ad 2)
  - if the reason is the compilers ability to understand directories and/or packages/namespaces/modules, then it will get solved in #914 
  - regardless, thank you for detailed explanation

So the question is, if this is basically duplicate composed of two issues ( #914 and #876 ) shall we close it, or do you want to keep the testing case i made for this ticket, for further development and testing?

**Comment by dgelessus** [comment] 2021-11-05 23:27
re. 1: I completely agree, this is definitely a bug. I'm just saying the bug is not related to relative imports or packages - the same thing happens when you import another .ksy from the same directory.

> So the question is, if this is basically duplicate composed of two issues ( #914 and #876 ) shall we close it, or do you want to keep the testing case i made for this ticket, for further development and testing?

Yep, I agree, we can probably close this as a duplicate of the other two. With GitHub's automatic backlinks, it's easy to find back to this issue, in case we need the test code from here.

**Closed by dgelessus** 2021-11-05 23:27 UTC
