### ISSUE TITLE
Cannot use _index inside "pos" key

### ISSUE THREAD

**Issue by whiteh0le** [kaitai-io/kaitai_struct#834] opened 2020-11-24 23:09 UTC
# Problem:
Let's say you encounter the following file format:
```yaml
meta:
  id: table_tb
  file-extension: tb
  endian: le
seq:
  - id: count
    type: u4
  - id: table_info
    type: table_info
    repeat: expr
    repeat-expr: count
instances:
  data:
    pos: table_info[_index].offset
    size: table_info[_index].size
    repeat: expr
    repeat-expr: count
types:
  table_info:
    seq:
      - id: offset
        type: u4
      - id: size
        type: u4
```
The format consist of a number of offsets and sizes that point to data, if we want to parse the data, we must use instances, the problem is, Kaitai doesn't allow the use of `_index` inside the `pos` key as it will throw us the following error message:
> Parse error: undefined
> Call stack: undefined TypeError: this.tableInfo[i] is undefined

The parse error occurs due to the Kaitai Struct Compiler generating the following code:
```javascript
[...]
Object.defineProperty(TableTb.prototype, 'data', {
  get: function() {
    if (this._m_data !== undefined)
      return this._m_data;
    var _pos = this._io.pos;
    this._io.seek(this.tableInfo[i].offset);
    this._m_data = new Array(this.count);
    for (var i = 0; i < this.count; i++) {
      this._m_data[i] = this._io.readBytes(this.tableInfo[i].size);
    }
    this._io.seek(_pos);
    return this._m_data;
  }
}
[...]
```
As you can see, the `this._io.seek` function is not inside the `for` loop and so, the `i` variable is not visible.
One could argue that you can just replace the `_index` variable inside `pos` by `0` and let the size do the rest:
```yaml
[...]
instances:
  data:
    pos: table_info[0].offset
    size: table_info[_index].size
    repeat: expr
    repeat-expr: count
[...]
````
But **this would only work if the data offset of an element is equal to the offset of the element before it + its size** which is not true for our file format.

# Possible Solution:
The solution would be to place the `this._io.seek` call inside the `for` **only when `pos` has the _index variable inside it** like so:
```javascript
[...]
for (var i = 0; i < this.count; i++) {
  this._io.seek(this.tableInfo[i].offset);
  this._m_data[i] = this._io.readBytes(this.tableInfo[i].size);
}
[...]
```
PD: I created this example file format to demonstrate the bug, I didn't use a real file format because it would be more complicated to point out the problem, but just to let you know, I've encountered this problem while reversing real file formats numerous times.

**Comment by Mingun** [comment] 2020-11-25 03:36
I think that your case can be trivially solved if you move `data` instance inside the `table_info` type and remove `repeat` key in it.

Making meaning of `pos` depending on the expression content is a bad idea: how, for example, you should process such definition:
```yaml
params:
- id: flag
  type: b1
instances:
  data:
    pos: flag ? _index : 42
```

All instance positions should be counted from the beginning of enclosed type (for top-level instances enclosed type is implicitly named as `meta/id` value). Right now that isn't true, because `pos` relative to the parsed stream which isn't the same -- not all types has it's own stream, only them which have an explicitly defined `size`.

**Comment by whiteh0le** [comment] 2020-11-25 05:56
>
> how, for example, you should process such definition: [...]

Sorry, I've been thinking about your example and I can't see the issue? If the overlying type has a defined size then it will have a substream and the position if the underlying type will be relative to that stream, if not, then the position will be relative to the `_root` stream just as it is now. Also, I think the `_index` variable is nos visible in that context, you should past it as a parameter, just like `flag`.

Again, sorry if I didn't understand your point, but my knowledge of Kaitai is still limited.

**Comment by Mingun** [comment] 2020-11-25 06:16
Sorry, I should be more specific. I've update example for clarifily. My point in that if you start generating code for position based on the usage of the `_index` var in it you'll face with the ambiguity, because `_index` usage is depending on the external factor and you should generate two different sources at the same time

**Comment by Mingun** [comment] 2020-11-25 06:47
In general, I agree that the current behavior of the `pos` is not obvious, because all other fields (`type`, `size`) apply to the element of array and only the `pos` is applied to the array field itself. From KSY reader point-of-view, it could be applied to both the entire array field and its individual elements. Since other fields are applied to elements, it is automatically assumed that `pos` is also applied to elements, especially since it often paired with `size`. IMHO, changing `pos` to always act as element start position is preferred way to solve the problem. In that case:
- if `pos` is omitted, then each element follows previous, the first element at the offset `0` from the beginning of the enclosing type (not the stream!)
- if `pos` is defined and...
  - ...`pos` is constant then all elements overlaps each other
  - ...`pos` depends on the `_index`, each element has its own position

Non-array instances behaves likely one-element array, i.e.:
- if `pos` is omitted, then data at the offset `0` from the beginning of the enclosing type (not the stream!)
- if `pos` is defined then data at the specified offset from the beginning of the enclosing type (not the stream!)

**Comment by Mingun** [comment] 2020-11-25 15:39
Duplicate of #436
#709 also maybe somehow related.

**Comment by generalmimon** [comment] 2020-11-26 07:11
@whiteh0le @Mingun Please always search the issue tracker before opening or commenting on a new issue. This topic has been discussed a dozen of times before, a list of links to related issues can be found in https://github.com/kaitai-io/kaitai_struct_doc/pull/35#issue-416394784. 

See the section [Keys relating to the whole array and to each element in repeated attributes](http://doc.kaitai.io/user_guide.html#keys-repeated) in the User Guide, which describes this pitfall and how to work around it.

Closing as duplicate of #436.

**Closed by generalmimon** 2020-11-26 07:11 UTC
Labels: duplicate
