### ISSUE TITLE
Compiler feature suggestion: parse-only or no-output

### ISSUE THREAD

**Issue by webbnh** [kaitai-io/kaitai_struct#290] opened 2017-11-07 16:40 UTC
It would be handy during certain phases of development to be able to run `ksc` without producing any output.  The seemingly-obvious way to do this doesn't work:
```
$ ksc -t cpp_stl --outdir /dev/null DjidatV3/Records/djidat.V3.3.ksy 
/dev/null/djidatv3.cpp (Not a directory)
$
```

I suggest either adding a "no-op" _target_ (e.g., `--target none`) or, perhaps better, a switch like `--no-output` or `--dry-run`, etc.  The former would be sufficient to my needs, but having the compiler actually generate my chosen target and then not save it would probably be better.

Thanks!

**Comment by GreyCat** [comment] 2017-11-07 17:18
Hmm, I believe it's duplicate of #177? If I'm mistaken, please don't hesitate to reopen.

**Closed by GreyCat** 2017-11-07 17:18 UTC
Labels: duplicate

**Comment by webbnh** [comment] 2017-11-07 18:15
Right you are!

(I did the due diligence search prior to entering my previous issue, but I failed to do so for this one -- my apologies!!)
