### ISSUE TITLE
Kaitai Struct as a Binary File Writer

### ISSUE THREAD

**Issue by prashantharaonr** [kaitai-io/kaitai_struct#765] opened 2020-06-27 19:57 UTC
Hi,
I have a question on the reverse process. Can Kaitai struct be used to write a binary file?

Let us say there is a binary file format defined as a .ksy file. A process incrementally appends chunks to this file. each chunk has a structure which in turn can be defined in a separate .ksy file. Such a .ksy file for a smaller chunk is mainly a subset of the binary file (expected end product) plus some small metadata at the chunk level to uniquely identify the chunk, its sequence, and locate the chunk in the bigger .ksy. The process may produce the chunks having different structures each time which in turn depends on the internal details of the process. Hence to write a binary file fully may have more than one .ksy file at the chunk level.

Is this possible?

Regards
Rao

**Comment by NN---** [comment] 2020-06-28 06:38
#27

**Comment by GreyCat** [comment] 2020-06-28 15:30
Indeed, seems to be duplicate of #27, so let's continue the discussion there. See also http://doc.kaitai.io/faq.html#writing

**Closed by GreyCat** 2020-06-28 15:30 UTC
Labels: duplicate, question
