### ISSUE TITLE
Java: incompatible types compile error when type that is reused is used in a type that is unreachable

### ISSUE THREAD

**Issue by Kh4n** [kaitai-io/kaitai_struct#961] opened 2022-04-14 06:32 UTC
Here is a buggy .ksy:
```yaml
meta:
  id: bug
  file-extension: na
  endian: le
seq:
  - id: body
    type: type_inner
# uncomment to fix bug
#  - id: body2
#    type: type_unused
types:
  type_reused:
    seq:
      - id: count
        type: s4
  type_inner:
    seq:
      - id: file_name
        type: type_reused
  type_unused:
    seq:
      - id: source_code_loc
        type: type_reused
```
The compile error is: 
```
/home/kh4n/Documents/jt-loader/target/generated-sources/kaitai/name/kh4n/jtloader/Bug.java:[110,59] incompatible types: name.kh4n.jtloader.Bug.TypeUnused cannot be converted to name.kh4n.jtloader.Bug.TypeInner
```
It is caused because `type_reused` (generated as `TypeReused`) has its `_parent` set to `Bug.TypeInner`:
```java
        public TypeReused(KaitaiStream _io, Bug.TypeInner _parent, Bug _root) {
            super(_io);
            this._parent = _parent;
            this._root = _root;
            _read();
        }
...
```
If you uncomment this becomes:
```java
        public TypeReused(KaitaiStream _io, KaitaiStruct _parent, Bug _root) {
            super(_io);
            this._parent = _parent;
            this._root = _root;
            _read();
        }
```
as it should. Manually changing the generated file also works. Not a huge issue because you can just use the type somewhere, but worth mentioning nonetheless as it is pretty common to have a type defined and then used somewhere that is currently unreachable as you are prototyping, which can be very confusing to debug.

I think it might be caused by an optimization which notices that `type_unused` is unreachable so it makes `type_reused`'s parent `type_inner` (the only place it is technically used) but then the `type_unused` code is still emitted. I don't know the code base but if someone points me to possible file(s) I can try to fix the issue :). I will try my best to solve it on my own.

**Comment by generalmimon** [comment] 2022-04-16 07:08
Nice catch. My hypothesis is that when KSC derives types of `_parent` parameters, the entry point is the top-level `seq` and `instances` and then it proceeds recursively to all the types used there. Therefore, types that are not reachable by traversing the dependency tree with the top-level `seq`+`instances` as the root node are not processed at all by the type derivation KSC component. It's as if they don't even exist.

This perfectly matches another related problems in unused types (it seems that no issues have been created for these, because I've only noted them on my personal list of KS bugs without associated issues):

> - unused `types` sometimes trigger a compile-type exception due to unability to deduce `_parent` type (this reminded me of it: https://github.com/sonusz/PhasorToolBox/blob/ca9c5a6d35409a369ac73738b0c5e7621fec3bea/kaitai/data.ksy#L5-L11)
> - unused `types` are not checked for param mismatch
> 
>   ```ksy
>   meta:
>     id: params_mismatch_unused_type
>   types:
>     uses_foo:
>       seq:
>         - id: t
>           type: foo  # expected to accept a boolean argument and doesn't do so -> this is not reported
>     foo:
>       params:
>         - id: a
>           type: bool
>   ```

**Comment by Kh4n** [comment] 2022-04-18 06:04
Looking through JavaCompiler and NoNeedForFullClassPath, these seem relevant?

**Comment by Mingun** [comment] 2024-03-13 17:12
This is duplicate of #414.

**Closed** 2024-04-15 21:21 UTC
Labels: bug found
