### ISSUE TITLE
Generated python code does not import properly

### ISSUE THREAD

**Issue by nosajthenitram** [kaitai-io/kaitai_struct#987] opened 2022-08-21 01:42 UTC
I have a main.ksy file, which imports another import_1.ksy file defining a sequence and some types. The import_1.ksy imports a common_types.ksy file, which defines some common types used in multiple places throughout the code.

When I compile the main.ksy file, I end up with references to the common_types.py in my import_1.py source but the common_types.py import is missing from the top of my generated python.

**Comment by dgelessus** [comment] 2022-08-21 11:22
Duplicate of #703 probably.

**Closed by dgelessus** 2022-08-21 11:22 UTC
