### ISSUE TITLE
Add support for repeated field callbacks

### ISSUE THREAD

**Issue by sweetgiorni** [kaitai-io/kaitai_struct#856] opened 2021-03-05 07:05 UTC
First of all, very cool project! I might contribute if I have time.

Forgive me if this functionality already exists, but I couldn't find anything:

When working with large files, it may be helpful to invoke a user-provided callback for each entry in a repeated field, as opposed to storing all entries in memory. This way, if the user only needs a subset of the data in the binary file, they can parse the entire file and manually allocate memory for the data they need. This would allow KSC to perform well with arbitrarily large files.

While this would be most helpful for repeated fields, I'm sure something similar could be done for non-repeated fields.

Obviously the implementation of this feature would be very language dependent, and some languages might not have native support for this at all.

**Comment by KOLANICH** [comment] 2021-03-05 07:23
Not currently possible. It wasn't the model for which KS was designed.

See #263 about for some discussion about your use case.

**Comment by generalmimon** [comment] 2022-06-15 12:03
Duplicate of #449

Please continue the discussion there if you have further comments.

**Closed by generalmimon** 2022-06-15 12:03 UTC
Labels: enhancement, duplicate
