### ISSUE TITLE
Question: Can I use Kaitai in opposite direction? (manually fill structure with data->create stream from structure->write raw data f.e. to file)

### ISSUE THREAD

**Issue by iboofkratom** [kaitai-io/kaitai_struct#1003] opened 2022-12-22 15:21 UTC
Hi,
I have a question. I know Kaitai can be used to parse raw data into data structures. And I really like it for this purpose.
But can Kaitai also be used for the opposite process?
For example - what if I wanted to use it for creating communication protocols (custom packets):
On one side I want to recieve a packet and parse it. I know Kaitai can do this.
But on the other side, I would like to fill my custom data structure with data and than create raw data stream from it, which could be sent to the first device.
Is this possible with Kaitai? Sorry for noob question.
Thanks!!

**Comment by generalmimon** [comment] 2022-12-22 15:37
Duplicate of #27

**Comment by generalmimon** [comment] 2022-12-22 15:38
> But on the other side, I would like to fill my custom data structure with data and than create raw data stream from it, which could be sent to the first device.
> Is this possible with Kaitai? Sorry for noob question.

Not yet, see https://doc.kaitai.io/faq.html#writing.

**Closed by generalmimon** 2022-12-22 15:37 UTC
Labels: enhancement, duplicate

**Comment by iboofkratom** [comment] 2022-12-22 15:39
Okay, thanks for the response!

**Comment by iboofkratom** [comment] 2022-12-22 15:45
Okay, thanks for response!
