### ISSUE TITLE
Improvements for importYaml() in the js version of ksc

### ISSUE THREAD

**Issue by fallenoak** [kaitai-io/kaitai_struct#268] opened 2017-09-26 03:23 UTC
While working on adding `meta.imports` support to `kaitai-struct-loader`, I've noticed that it's quite tricky to track the current directory as `ksc` traverses imports. Doing so is necessary in order to construct the full path to the file on disk for loading in `importYaml()`.

Because there's no way to relate the call to `importYaml()` back to the parent `ksy` requesting the import, I'm not aware of a way I can always correctly resolve the full path on disk for imports, particularly when dealing with sibling imports from varied paths.

Per @koczkatamas's suggestion the other day, perhaps `importYaml()` could be simplified to something like: `importYaml(path)`, where `path` either:

* starts with a `/` to denote an absolute path
* or is a path relative to the _initial_ `ksy` being passed into `compile()`

This would likely require passing in the initial `ksy` path to `compile()` and adding some path handling logic to `ksc`.

I realize this might not be ideal. An alternative might be to change how `compile()` works, such that `importYaml()` can tie the import back to the `ksy` requesting the import. Not quite sure what that might look like.

**Comment by koczkatamas** [comment] 2017-09-26 07:43
> This would likely require passing in the initial ksy path to compile() and adding some path handling logic to ksc.

I don't think this is necessary, it's enough if the JSImporter knows the initial ksy path, so the `importYaml` can read it from an instance field and not from a method argument.

Of course sometimes the relative path sent to the `importYaml` method will start with `../`, but this is the expected behavior.

Sending the initial ksy path is not a good idea IMHO if for example the compiler is run on Windows then it can be `C:\somefolder\sometype.ksy` or maybe even more complicated with virtual filesystems. The V2 IDE for example uses URLs everywhere, ex. `browser:///something.ksy` or `github://kaitai-io/kaitai_struct_formats/archive/zip.ksy`, so it's just better if the compiler does not even try to handle these paths. Let's leave this to the importer module.

**Comment by GreyCat** [comment] 2017-09-26 07:45
Hmm, is it duplicate of #212?

**Comment by fallenoak** [comment] 2017-09-26 12:04
Allow me to demonstrate what I believe to be currently impossible without at least changing how `compile()` works:

```
-> root/
   -> root.ksy
      -> dir1/
         -> foo.ksy
         -> subdir1/
            -> bar.ksy
      -> dir2/
         -> baz.ksy
         -> subdir2/
            -> bom.ksy
```

root.ksy:

```yaml
meta:
  id: root
  imports:
    - dir1/foo
    - dir2/baz
```

foo.ksy:

```yaml
meta:
  id: foo
  imports:
    - subdir1/bar
```

baz.ksy:
```yaml
meta:
  id: baz
  imports:
    - subdir2/bom
```

**Comment by fallenoak** [comment] 2017-09-26 12:12
I don't believe this is a dupe of #212, although I was initially leaning toward that. In JS, the entire responsibility for understanding the filesystem currently falls on the code that implements `importYaml()` (in my case, that'd be inside `kaitai-struct-loader`).

**Comment by koczkatamas** [comment] 2017-09-26 12:42
@fallenoak in my suggesion `importYaml` would be called by the compiler with the following paths: `dir1/foo`, `dir1/subdir1/bar`, `dir2/baz`, `dir2/subdir2/bom`.

The compiler can track the current relative directory even it does not know anything about the original path of the `root.ksy` (which is `root/root.ksy` in the example).

**Comment by fallenoak** [comment] 2017-09-26 13:07
@koczkatamas D'oh! Totally misunderstood that. Must not have had enough coffee today. That'd be perfect, I think!

@GreyCat Does @koczkatamas suggestion work for you?

**Comment by GreyCat** [comment] 2017-09-26 13:09
Yeah, that's exactly what we were talking about in #212. So, let me finish that one and see if that would work for all of us ;)

**Closed by GreyCat** 2017-09-26 13:09 UTC

**Comment by GreyCat** [comment] 2017-09-26 13:13
Actually, not only that, but also more complex stuff like that should work:

1. Ask for absolute import like `/something/foo` => importYaml gets queried for that => it finds `something/foo.ksy` in some library/central repo path
2. That one asks for relative import like `bar/baz` => ksc derives that we need to import `/something/bar/baz.ksy` => importYaml gets that and finds that (may be in some other search path, not necessarily in the same path where it found `/something/foo.ksy` originally).
