### ISSUE TITLE
cpp_stl generator does not use type kaitai::kstruct* for m_data, if only 1 switch-on and default case

### ISSUE THREAD

**Issue by tangoalx** [kaitai-io/kaitai_struct#609] opened 2019-08-08 09:22 UTC
Let's assume a ksy similar to this:

```yml
seq:
      - id: record_type
        type: u2
      - id: record_body
        type:
          switch-on: record_type
          cases:
            0x1111: packet1
            #0x1112: packet2     # <--- must be defined
            _: record_body_unknown

types:
  packet1:
    seq:
      - id: id
        type: u4
      - id: data
        size-eos: true
        
#  packet2:
#    seq:
#      - id: magic1
#        contents: [0xcd, 0xcd]
#      - id: id
#        type: u4
#      - id: data
#        size-eos: true

  record_body_unknown:
    seq:
      - id: data
        size-eos: true
```

When thre is only `packet1` and the default case `record_body_unknown` in the switch-on `record_type`, then `m_data` member will have the type `packet1*`. If the `packet2` is enabled, then the type is `kaitai:kstruct*`. The type must be `kaitai::kstruct*` because of the generated `packet1* data()` method, which cannot return a `record_body_unknown*` member. This leads to a compiler error.
However the return value of the `data()` method automatically changes by enabling `packet2`, too.

As there is a work-around known, this issue probably does not have a high priority.

**Comment by GreyCat** [comment] 2019-09-05 08:50
Clearly a bug, thanks for reporting this!
Any chance I can ask you to add relevant test to our [test suite](https://github.com/kaitai-io/kaitai_struct_tests/tree/master/formats)?

**Comment by zmarvel** [comment] 2019-10-18 03:07
I'm interested in contributing to this project, and this looks like it might be a good first issue. I can build the compiler and test suite. I can also reproduce this behavior.

@GreyCat, as a first step, I'm happy to add a test case for this behavior. Next, looking at `CppCompiler.scala`, it looks like this is caused by the exclusion of `SwitchType.ELSE_CONST` members in `combineSwitchType`. I don't understand why these types are excluded--would you mind clarifying?

**Comment by generalmimon** [comment] 2020-05-18 19:51
This has been fixed in https://github.com/kaitai-io/kaitai_struct_compiler/commit/c5be95a293cb78cb95088de250214f0cc727b365. The problem was that the "else case" wasn't taken into account at all when combining the switch case types, so it ended up with the `packet1` type, which is the only non-else case in the example.

@zmarvel Here's why C++ doesn't include the default `BytesType` case if present in the `switch`: [`CppCompiler.scala:1073-1077`](https://github.com/kaitai-io/kaitai_struct_compiler/blob/c5be95a293cb78cb95088de250214f0cc727b365/shared/src/main/scala/io/kaitai/struct/languages/CppCompiler.scala#L1073-L1077)

**Closed by generalmimon** 2020-05-18 19:51 UTC
Labels: bug found
