### ISSUE TITLE
release cycle length?

### ISSUE THREAD

**Issue by arekbulski** [kaitai-io/kaitai_struct#326] opened 2018-01-25 17:24 UTC
I need to ask, how long does it take between Kaitai releases? For example, if I dont finish a Python or C# PR patch on time before 0.8, will it take a year or so before it gets shipped?

**Comment by GreyCat** [comment] 2018-01-25 17:33
Currently, there's no fixed schedule. Initially, I expected to push a new release once per 2-3 months. Current situation is, of course, outrageous, so, to break a bad habit, we'll need to build some infrastructure to make these releases easier.

I see that there are several time-consuming tasks for a release:

* Preparing a changelog. Hardly anything can be done about that, except for trying to grow changelog entries as the project progresses, not "let's sit down and try to document 100500 commits that happened at once".
* Tagging everything, building everything, testing everything and publishing everything. "Everything" has grown substantially now. Long ago, I was publishing 3 packages from one source — Debian compiler, Windows compiler, .zip compiler. Nowadays, it's 3 compiler packages + ksv + most the runtimes, and, ideally, we'll need to throw it some more builds (NuGet, Chocolatey, etc). This drastically needs to be automated.
* Announcing new release. Again, there's no way to escape lots of manual text composing, but, again, it can be mitigated somehow by (1) splitting this job between several people, (2) having a hard plan on what we should do and what we shouldn't.

**Comment by arekbulski** [comment] 2018-01-25 17:51
I will finish the tickets assigned to me before 0.8 then. :expressionless:

**Comment by KOLANICH** [comment] 2018-01-25 18:28
I guess that release cycle should be ... a single commit. Yes, I think for such kind of projects bleeding edge is the best solution.

So

1 Every nightly passing the test suite should be linked to kaitai.io
2 Is someone finds a valid code causing malfunction, he should create an issue. According to the issue the test should be created and added to the test suite. Then the release history should be bisected against that test and the builds should be marked as not passing that test.

3 On kaitai.io there should be n+2 versions: the latest nightly, the latest build passing all the test suite, and the latest build passing all the test suites except ```i``` last added tests (for ```i``` from 1 to ```n```)

**Comment by GreyCat** [comment] 2018-01-25 18:32
Um, for starters, we don't have a "build passing all the test suite", and never had one before. Current coverage for different targets is close to 100%, but, unfortunately, not 100%.

Nightly builds is a great thing, and it actually is, ironically, available for Windows only. But full-featured releases is a different beast: it's less about actual programming and features, but more like a PR event. We need to remind people of our project from time to time. If that happens too often, that's bad. If that happens rarely, that's bad too.

**Comment by KOLANICH** [comment] 2018-01-25 19:09
As a newsbreak I guess a single language feature is enough. I guess the headline "Templates are implemented in Kaitai Struct" is mucch better than "Kaitai Struct hit the version 1.0". But kaitai.io should always give the users the link to nightly.

And there is no problem (if a one has either wine or lessmsi working) to unpack the files from msi and use them on linux, that's why I have not created an issue about nightlies for linux - we already have them.

**Comment by arekbulski** [comment] 2018-01-25 21:19
Guys, we are getting sidetracked here. Daily releases do not necessitate daily PR campaigns. And test suite not passing 100% does not prevent daily releases. 

**We do not need daily releases, we need weekly or monthly releases.**

@GreyCat  I recommend to you that we dedicate next milestone strictly to
- improving test suites, fix what can be fixed in moderate time, and mark remaning ones as xfail-alike
- improving Travis suite
- writing for-developers tutorials how to do packaging (like NuGet) so that someone else can take over 
- assigning people like Arlorean to managing per-target packaging, 
- automating build process where humanly possible

**Comment by GreyCat** [comment] 2018-01-25 22:51
@arekbulski Completely agree with you. The next focus should be on infrastructure.

**Comment by arekbulski** [comment] 2018-01-26 01:48
Some pointers for later

> Preparing a changelog.
> let's sit down and try to document 100500 commits

We only need summaries, and only for most important things too, which for short release cycle should not that long. Think of changelogs as PR pamphlets, not technical detailed complete specs. That approach makes it easier.

> trying to grow changelog entries as the project progresses

I follow that rule in Construct (altough I failed at that at few occasions, people get tired, things slip)

> building everything, testing everything and publishing everything.

For building and testing, thats what we have Travis for. And test suite. And benchmark suite. Holy shit.

For publishing, we should write a short tutorial. It doesnt need to be detailed or hold-your-hand-while-you-type-it but just so that another person could take over if needed. Honestly, I am yet to grasp how to git clone main repo with sub-repos, or how to run test suite locally on a PR. 

Construct can push to pypi with 2 lines
```bash
./setup.py build sdist
twine upload dist/...targz
```

> having a hard plan on what we should do and what we shouldn't.

Yes.

**Comment by GreyCat** [comment] 2018-01-26 01:55
> For building and testing, thats what we have Travis for. And test suite. And benchmark suite. Holy shit.

The problem is that you can't test *everything* with Travis. I mean, *after* making up packages, you need to ensure that they are installable (in Windows, for example, it means clicking on tons of "Next" button, in Debian that requires root permissions, etc), and when ran, it at least gives some sane output. Unfortunately, there are tons of way to screw up packaging. It's not like it is *impossible* to make automated tests for that, but, IMHO, at least for now, it's not worth it.

> For publishing, we should write a short tutorial.

Actually, there is one: http://doc.kaitai.io/developers.html#_publishing_a_new_version

> Honestly, I am yet to grasp how to git clone main repo with sub-repos, or how to run test suite locally on a PR.

`git clone --recursive` is your friend. If you don't want to do full re-clone, then `git submodule update --init --recursive` should work.

**Comment by arekbulski** [comment] 2018-01-26 01:59
I would recommend to you for your consideration, the following approach, as I used it in Construct for past 2 years. We switch to say weekly (beta) releases and a rule: PR must include a test case  and proper documentation to be mergable. Everything that is WIP remains in non-master branches until finished. This implies master branch is at any point ready to ship. :kissing_closed_eyes:

**Comment by arekbulski** [comment] 2018-01-26 02:11
I appologise for not doing more for Kaitai. I am currently working on a major feature in Construct (a compiler) and as of now its 50 open tickets and 50 closed. And as I work on tickets, new ones get added. Holy shit. :confused:

**Comment by arekbulski** [comment] 2018-01-26 02:43
> The problem is that you can't test everything with Travis.

I think you are somewhat looking at it the wrong way. We dont need to "check everything". We just make sure that the build and packaging process is sound, and then we ship regularly using that process. If something gets broken, someone will come and notify us. Think of it as deferring the testing to end user. :smile: 

And we are talking about regular BETA releases.

**Comment by arekbulski** [comment] 2018-01-26 03:17
Its not April Fools today but I had a funny ticket lately and wanted to share it with you. In case you are wondering, the "debating to death in a comittee" was indeed, about Kaitai. 
https://github.com/construct/construct/issues/428

I dont mean to depreciate what you guys are doing, quite the opposite in fact, but I think this entire project, became somewhat too fat and slow for its own sake. I am no leader of men, holy shit no, but I learned from my mistakes and would like to help you deal with yours. Problems need to be pointed out and blantly, pride swallowed, consensus made, nods shaken, moved on. I think we are slooowly geting out of phase one, or rather somewhere in the middle of it. :confused:

**Comment by arekbulski** [comment] 2018-01-27 03:29
Found this release history on pypi, a little gem... look at dates (differences)
https://pypi.org/project/kaitaistruct/#history

**Comment by KOLANICH** [comment] 2018-01-27 07:45
>you can't test everything with travis

I wonder if it is possible to install wine there and test Windows version using wine and something like autoit or neosignofmisery

**Comment by arekbulski** [comment] 2018-01-27 15:08
> The problem is that you can't test everything with Travis. I mean, after making up packages, you need to ensure that they are installable (in Windows, for example, it means clicking on tons of "Next" button, in Debian that requires root permissions, etc), and when ran, it at least gives some sane output. Unfortunately, there are tons of way to screw up packaging. It's not like it is impossible to make automated tests for that, but, IMHO, at least for now, it's not worth it.

It seems to me like you are talking about testing the installer builder/packager rather than testing Kaitai. Guys, we are getting sidetracked here. Python has daily builds, ...do you really think... they are (auto/manually) testing their exe/msi installers if the Next button clicks right?

**Comment by KOLANICH** [comment] 2018-01-27 15:23
Yes, we are really sidetracked. Under the tests I initially meant the set the additional set of kaitai definitions which is meant to be used only for compiler testing, the set of binary files (corresponding to each format in a library + dedicated test suite) to parse, the system grabbing the latest compiler, library and dedicated testsuite, compiling them, parsing, converting parsed objects into comparable outputs and comparing to the reference outputs, and the set of reference outputs themselvss.

**Closed** 2018-01-30 06:42 UTC
Labels: infrastructure
