### ISSUE TITLE
Combining arrays

### ISSUE THREAD

**Issue by SpenserStyles** [kaitai-io/kaitai_struct#234] opened 2017-08-28 09:56 UTC
Say I have something like this:
`[CHUNK_START_1][CHUNK_START_2][CHUNK_START_3][CHUNK_1][CHKSUM][CHUNK_2][CHKSUM][CHUNK_3][CHKSUM]`

Now I can parse the chunks based on the start addresses doing something like this:
```
- id: chunks
  size: start_address[_index + 1] - start_address[_index]
  repeat: expr
  repeat-expr: num_chunks
```

So now I have chunks that contains 3 arrays.  I need to parse the 3 chunks as if they are a single array (single substream).  Is this possible?

**Comment by koczkatamas** [comment] 2017-08-28 10:12
I think it's the duplicate of https://github.com/kaitai-io/kaitai_struct/issues/196

Please continue the discussion there!

**Closed by koczkatamas** 2017-08-28 10:12 UTC
