### ISSUE TITLE
Short option for output directory does not work

### ISSUE THREAD

**Issue by m-ka** [kaitai-io/kaitai_struct#464] opened 2018-08-06 11:32 UTC
The compiler's help message mentions the `-d` and `--outdir` options for output directory. `ksc -t python --outdir build resizable_bar.ksy` works as expected, but `ksc -t python -d build resizable_bar.ksy` does not work and produces the following output:
```
[residual] arg = 'build'
[residual] arg = 'resizable_bar.ksy'
# Executing command line:
java
-cp
/usr/share/kaitai-struct-compiler/lib/io.kaitai.kaitai-struct-compiler-0.9-SNAPSHOT.jar:/usr/share/kaitai-struct-compiler/lib/org.scala-lang.scala-library-2.12.4.jar:/usr/share/kaitai-struct-compiler/lib/com.github.scopt.scopt_2.12-3.6.0.jar:/usr/share/kaitai-struct-compiler/lib/com.lihaoyi.fastparse_2.12-1.0.0.jar:/usr/share/kaitai-struct-compiler/lib/com.lihaoyi.fastparse-utils_2.12-1.0.0.jar:/usr/share/kaitai-struct-compiler/lib/com.lihaoyi.sourcecode_2.12-0.1.4.jar:/usr/share/kaitai-struct-compiler/lib/org.yaml.snakeyaml-1.16.jar
io.kaitai.struct.JavaMain
-t
python
build
resizable_bar.ksy

build (Is a directory)
```

**Comment by GreyCat** [comment] 2018-08-06 17:35
Duplicate of https://github.com/kaitai-io/kaitai_struct/issues/289

**Closed by GreyCat** 2018-08-06 17:35 UTC
