### ISSUE TITLE
Import statement is not inserted when only a enum is used.

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct#780] opened 2020-07-21 19:28 UTC
To reproduce compile bluetooth_hcd from https://github.com/kaitai-io/kaitai_struct_formats/pull/305 and see that https://github.com/kaitai-io/kaitai_struct_formats/pull/305/files#diff-d5dc77b92e2d98a1f9ab5b90cbdb3fe4R21 doesn't cause `BluetoothVendorsIds` be imported.

**Comment by dgelessus** [comment] 2020-07-21 19:38
I'm not sure, but this might be the same problem as #651.

**Comment by KOLANICH** [comment] 2020-07-21 19:46
That one errors in transpile time. This one errors in run time (at least for python).

**Comment by generalmimon** [comment] 2020-07-22 09:38
Actually, it's a duplicate of https://github.com/kaitai-io/kaitai_struct/issues/703#issuecomment-659329573. It seems that it doesn't matter if you reference a nested user-type or a nested enum type from the imported spec. I'll try to solve it in the near future.

> I'm not sure, but this might be the same problem as #651.

Thanks for pointing out issue #651, I didn't know about it (most likely because I often filter the issues by label "bug found", but that issue didn't have it until now). Yeah, it seems like the same problem as well.

> That one errors in transpile time. This one errors in run time (at least for python).

Apparently not anymore, you can see on the timeline of issue #651 that commit https://github.com/kaitai-io/kaitai_struct_compiler/commit/5d4881a290ad8b036a0760b23b3015f20c24eb5b solved the problem with the compiler failing to generate the parser. Now it really fails only at run time, as you can see in the [CI dashboard](https://ci.kaitai.io/) (search for test `EnumImport` that demonstrates the problem - here's the [`enum_import.ksy`](https://github.com/kaitai-io/kaitai_struct_tests/blob/master/formats/enum_import.ksy)). In Python it currently fails with `NameError: global name 'Enum0' is not defined`, which again points to the missing import.

**Closed by generalmimon** 2020-07-22 09:38 UTC
Labels: bug found, duplicate

**Comment by generalmimon** [comment] 2024-03-21 10:50
Duplicate of #651
