### ISSUE TITLE
Compiler complains that Java 11 is too old :/

### ISSUE THREAD

**Issue by abitrolly** [kaitai-io/kaitai_struct#813] opened 2020-09-29 06:35 UTC
I downloaded JRE OpenJDK11U-jre_x64_linux_hotspot_11.0.8_10.tar.gz from https://adoptopenjdk.net/index.html and compiler 0.8 doesn't work with it.

```
✗ JAVA_HOME=kaitai-struct-compiler/jre kaitai-struct-compiler/bin/kaitai-struct-compiler

The java installation you have is not up to date
requires at least version 1.6+, you have
version 11.0.8

Please go to http://www.java.com/getjava/ and download
a valid Java Runtime and install before running .
```

**Comment by KOLANICH** [comment] 2020-09-29 06:48
>Compiler

Please call Katai Struct Compiler as `KSC`.

You can try to modify the shell script launching KSC.

**Comment by abitrolly** [comment] 2020-09-29 06:50
Downloaded [Universal .zip](https://dl.bintray.com/kaitai-io/universal/0.8/kaitai-struct-compiler-0.8.zip) from https://kaitai.io/#download

**Comment by abitrolly** [comment] 2020-09-29 06:52
@KOLANICH there is no `ksc` in this distribution.

**Comment by GreyCat** [comment] 2020-09-29 10:11
Duplicate of #483. Already fixed in modern versions, can be worked around with `-no-version-check` with existing releases.

**Closed by GreyCat** 2020-09-29 10:11 UTC

**Comment by abitrolly** [comment] 2020-10-01 13:54
@GreyCat thanks. Missed that ticket.
