### ISSUE TITLE
ksc has incorrect usage text

### ISSUE THREAD

**Issue by howardjones** [kaitai-io/kaitai_struct#938] opened 2021-12-15 12:35 UTC
ksc 0.9 claims that -d can be used to specify the output directory. Looks like it actually enables debugging.

```
kaitai-struct-compiler 0.9
Usage: kaitai-struct-compiler [options] <file>...

  <file>...                source files (.ksy)
  -t, --target <language>  target languages (graphviz, csharp, rust, all, perl, java, go, cpp_stl, php, lua, python, nim, html, ruby, construct, javascript)
  -d, --outdir <directory>
                           output directory (filenames will be auto-generated)
```

--outdir does work.

**Comment by generalmimon** [comment] 2022-01-21 14:34
Duplicate of https://github.com/kaitai-io/kaitai_struct/issues/289

**Closed by generalmimon** 2022-01-21 14:34 UTC
Labels: bug found, duplicate
