### ISSUE TITLE
enum directive ignored in params list

### ISSUE THREAD

**Issue by webbnh** [kaitai-io/kaitai_struct#413] opened 2018-04-09 18:51 UTC
```
type:
  # ...
  payload:
    params:
    - id: rec_type
      enum: rec_types
      type: u1
    seq:
    - id: data
      #process: xor(0)
      type:
        cases:
          rec_types::type_1: type_1
          rec_types::type_2: type_2
        switch-on: rec_type
```
Produces errors, such as:
```
/types/payload/seq/0/type/cases/EnumByLabel(identifier(rec_types),identifier(type_2)): can't compare Int1Type(false) and EnumType(List(rec_types),CalcIntType)
```
(See [Lobby discussion](https://gitter.im/kaitai_struct/Lobby?at=5acbb331080a38505313c74b).)

**Comment by GreyCat** [comment] 2018-04-09 18:58
Ok, just for clarity, this seems to be caused not by type switching, so basically anything like that should reproduce the bug:

```yaml
meta:
  id: params_enum
enums:
  animals:
    1: cat
    2: dog
seq:
  - id: one
    type: u1
    enum: animal
  - id: invoke_with_param
    type: with_param(one)
types:
  with_param:
    params:
      - id: enumerated_one
        type: u1
        enum: animal
    instances:
      is_cat:
        value: enumerated_one == animals::cat # would break if there's a bug
```

**Comment by zolo** [comment] 2018-10-18 13:35
I'd like to see enum param support as well. A workaround is to pass ints and cast the cases using `to_i`

**Comment by GreyCat** [comment] 2018-10-22 07:57
Actually, I've just checked, support for enums in params was implemented ages ago: https://github.com/kaitai-io/kaitai_struct_compiler/commit/41e9a067d78d8f2855f47a4f44bcd2874b2e3c88

I've just added test to confirm that — see ParamsEnum: http://kaitai.io/ci/

**Comment by KOLANICH** [comment] 2018-10-23 09:50
Have just checked on the latest ver from appveyor, doesn't work on this file: https://github.com/KOLANICH/kaitai_struct_formats/blob/mdt/scientific/nt_mdt/nt_mdt.ksy#L89

**Comment by GreyCat** [comment] 2018-10-24 02:14
Thanks, caught yet another problem ;) New version should be available in ~15 minutes, please try again?

**Comment by KOLANICH** [comment] 2018-10-25 14:20
Still fails. Could you test on the spec I have referenced?

**Comment by GreyCat** [comment] 2018-10-25 14:23
That exact spec you're referring to is obviously broken, at least in respect supplying "type" as enum, and then switching over it as it was an integer. Here's a slightly fixed version that I was testing upon: https://gist.github.com/GreyCat/e99663ca7cbc31300c07ddea9352677d

If you're still getting an error, please state (1) which .ksy file exactly you're using, (2) what error you're getting.

**Comment by GreyCat** [comment] 2018-11-25 14:45
No replied for 1 month, from my perspective everything was fixed. Closing for now, please feel free to reopen if you still have repro.

**Closed by GreyCat** 2018-11-25 14:45 UTC
Labels: bug found

**Comment by KOLANICH** [comment] 2018-12-17 17:08
>Here's a slightly fixed version that I was testing upon: https://gist.github.com/GreyCat/e99663ca7cbc31300c07ddea9352677d

That works, thank you.

**Comment by trejkaz** [comment] 2019-07-11 08:57
I see this issue both on https://ide.kaitai.io/ and on https://ide.kaitai.io/devel right now. Same workaround of adding `.to_i` fixes it for me. It's quite possible that the deployed versions are out of date, but exactly how out of date?

**Comment by GreyCat** [comment] 2019-07-11 14:24
@trejkaz Unfortunately:

1. IDE deployment is broken now :( You can see deployed versions in about box.
2. We never had automated deployment of new versions of *compiler*.
3. Publications of JS versions of *compiler* to npmjs might be broken as well :(

**Comment by trejkaz** [comment] 2019-07-15 00:47
Hmm, so what's the path right now for getting a working IDE of some sort to work with KTS files? I had planned to some day make my hex viewer able to deal with them but it's probably a lot of work to get that up and going.
