### ISSUE TITLE
Serialization support

### ISSUE THREAD

**Issue by dakhnod** [kaitai-io/kaitai_struct#1140] opened 2024-10-27 00:37 UTC
Hey, thanks for your great Idea and work!

I would love to include Kaitai into Gadgetbridge, since that would make information hidden somewhere in code reusable in other languages.

As far as I can see, the serialization branch is not really supported. Is there any way to get serialization merged into the main branch? Or maybe at least have the serialization branch updated to the newest state?

Thanks,
Regards,
Daniel

**Comment by generalmimon** [comment] 2024-10-27 08:32
Duplicate of https://github.com/kaitai-io/kaitai_struct/issues/1060

**Closed by generalmimon** 2024-10-27 08:32 UTC
Labels: infrastructure, duplicate
