### ISSUE TITLE
Compiler unit tests seem to fail

### ISSUE THREAD

**Issue by mikehearn** [kaitai-io/kaitai_struct#972] opened 2022-06-21 15:48 UTC
The tests section of the developer memo is TODO so I'm not sure I'm doing this right, but the tests seem to fail (on master) with this error when running `sbt test`

```
[info] *** 1 SUITE ABORTED ***
[info] *** 56 TESTS FAILED ***
[error] Failed tests:
[error] 	io.kaitai.struct.translators.TranslatorSpec
[error] Error during tests:
[error] 	io.kaitai.struct.ErrorMessagesSpec
[error] (compilerJVM / Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 6 s, completed Jun 21, 2022, 5:47:20 PM
```

**Comment by generalmimon** [comment] 2024-07-20 18:42
Duplicate of #852

**Closed by generalmimon** 2024-07-20 18:42 UTC
Labels: infrastructure, duplicate
