### ISSUE TITLE
Java: Object name confusion

### ISSUE THREAD

**Issue by WaterKnight** [kaitai-io/kaitai_struct#1075] opened 2023-11-12 15:54 UTC
Hi,

just tried naming a type "object" in the .ksy file and then generating a parser for Java. The class will be named "Object" in Java. But my .ksy also had a field with an alternating type, which, too, becomes "Object" in the generated class. With the nested custom "Object" type in place, it thinks that this was meant, but it should actually be java.lang.Object. It would probably be similar for other inbuilt types.

https://github.com/WaterKnight/Warcraft3-Formats-KaitaiStruct/blob/2b8450d49c4e1af0bc36d56a1204bf059e777b2f/w3-w3a.ksy

Kaitai Struct Release: 0.10

**Comment by generalmimon** [comment] 2023-11-12 16:16
Duplicate of https://github.com/kaitai-io/kaitai_struct/issues/90

**Closed by generalmimon** 2023-11-12 16:16 UTC
Labels: bug found, duplicate
