### ISSUE TITLE
`imports` not generating working Python code

### ISSUE THREAD

**Issue by bersbersbers** [kaitai-io/kaitai_struct#1000] opened 2022-11-14 18:04 UTC
`payload.ksy`:
```yaml
meta:
  id: payload
  imports:
    - utility
seq:
  - id: packets
    type: utility::packet_t
    repeat: eos
```

`utility.ksy`:
```yaml
meta:
  id: utility
types:
  packet_t:
    seq:
      - id: packet
        type: u1
```

```
kaitai-struct-compiler.bat payload.ksy -t python
python -c "from payload import Payload; Payload.from_file('payload.py')"
```

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\bers\.pyenv\pyenv-win\versions\3.11.0\Lib\site-packages\kaitaistruct.py", line 44, in from_file
    return cls(KaitaiStream(f))
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Code\kaitai\payload.py", line 15, in __init__
    self._read()
  File "C:\Code\kaitai\payload.py", line 21, in _read
    self.packets.append(Utility.PacketT(self._io, self, self._root))
                        ^^^^^^^
NameError: name 'Utility' is not defined
```

**Comment by bersbersbers** [comment] 2022-11-14 18:51
Sounds a lot like #703. `ks-opaque-types: true` does not help.

**Comment by generalmimon** [comment] 2022-11-14 19:49
Duplicate of #703

**Closed by generalmimon** 2022-11-14 19:49 UTC
Labels: bug found, duplicate
