### ISSUE TITLE
Broken in 0.8, nullable instance produces missing declaration bug

### ISSUE THREAD

**Issue by GreyCat** [kaitai-io/kaitai_struct#355] opened 2018-02-12 17:02 UTC
Original was filed by @webbnh at https://github.com/kaitai-io/kaitai_struct_compiler/issues/127:

> I'm working on a reproducer; meanwhile, see the lobby chat from [here](https://gitter.im/kaitai_struct/Lobby?at=5a80faf118f388e6268f8c59) to [here](https://gitter.im/kaitai_struct/Lobby?at=5a81946cf283b8e5464f7b80).

**Comment by webbnh** [comment] 2018-02-12 17:43
Here's a cut-down reproducer:
```
enums:
  rec_types:
    1: rec1
meta:
  endian: le
  id: kscbug
  title: A reproducer for a bug in non-nullable instances
seq:
- id: fileheader
  type: fileheader
- doc: Having this reference satisfies type deduction requirements; the conditional
    allows us to defer reading it.
  id: records
  if: false
  type: record
types:
  rec1:
    seq:
    - id: fld0
      type: s2
  fileheader:
    seq:
    - id: device_type
      type: u4
  payload:
    instances:
      data:
        pos: 0
        size-eos: true
        type:
          cases:
            rec_types::rec1: rec1
          switch-on: _parent.type
  record:
    seq:
    - id: length
      type: u1
    - enum: rec_types
      id: type
      type: u2
    - id: payload
      if: length > 12
      size: length - 10 - 2
      type: payload
    - id: trailer
      type: u2
```

(My apologies for using the wrong tracker; thanks for moving the issue for me!)

**Comment by webbnh** [comment] 2018-04-07 03:52
So, I'm now caught in a dilemma:  I can't upgrade to V0.8 because of this bug, and I can't continue on V0.7 because of #209 (the memory leakage is crippling).

My way out would seem to be to get rid of the instance type (`payload` above) and to move the `cases` switch into the `record` type.  The problem is, while I believe that this works around the bugs, it also removes the lazy parsing, which I kind of like.  (I'll have to see how much it costs to lose it.)

Any thoughts?  (E.g., any idea whether the fix for this bug might become available Real Soon Now?)

Thanks!

**Comment by arekbulski** [comment] 2018-04-07 04:01
Is this bug actually C++ only? There is no explicit info about that.

**Comment by webbnh** [comment] 2018-04-07 04:27
I can't say...I'm only using C++.  :-)

**Comment by generalmimon** [comment] 2020-02-16 13:49
I'm closing this because I think this is resolved in https://github.com/kaitai-io/kaitai_struct_compiler/commit/d81ac0e4900e9882746854de5d70f07b78b07dca, feel free to reopen if is not.

**Closed by generalmimon** 2020-02-16 13:49 UTC
Labels: bug found
