### ISSUE TITLE
In `_debug` information of bit-granularity should be available

### ISSUE THREAD

**Issue by KOLANICH** [kaitai-io/kaitai_struct#896] opened 2021-08-23 21:14 UTC
It is needed for proper visualization in Hobbits (currently the info is got at byte granularity, so the visualization is inaccurate). It should also solve the issue of identifying bit-sized numbers type.

@hello-adam

**Comment by generalmimon** [comment] 2024-07-10 08:28
Duplicate of #333

**Closed by generalmimon** 2024-07-10 08:28 UTC
Labels: enhancement, duplicate
