### ISSUE TITLE
Trying to understand how nested types are resolved

### ISSUE THREAD

**Issue by wader** [kaitai-io/kaitai_struct#1019] opened 2023-04-11 09:57 UTC
Hello

I'm trying to understand how nested types and `::` it used to resolves types. Here is an example that confuses me:

```yaml
meta:
  id: nested_types
  endian: le
seq:
  - id: s0
    type: t0
instances:
  e0_hello_0:
    value: t0::e0::hello
  e0_hello_1:
    value: ::t0::e0::hello
  e0_hello_2:
    value: t0::t0::e0::hello
  e0_hello_3:
    value: t0::t0::t0::e0::hello
types:
  t0:
    seq:
      - id: t0s0
        type: u1
    enums:
      e0:
        1: hello
    types:
      t0:
        seq:
          - id: t0t0s0
            type: u2
        enums:
          e0:
            2: hello
```
Using https://ide.kaitai.io/ results in: (using the default zip input)
```json
{
  "s0": {
    "t0t0s0": 19280
  },
  "e0Hello0": { "name": "HELLO", "value": 2 },
  "e0Hello1": { "name": "HELLO", "value": 2 },
  "e0Hello2": { "name": "HELLO", "value": 2 },
  "e0Hello3": { "name": "HELLO", "value": 2 }
}
```
`type: t0` seems to resolve to the nested "`t0::t0`", if i rename it to "`t0::t1`" the result is:
```json
{
  "s0": {
    "t0s0": 80
  },
  "e0Hello0": { "name": "HELLO", "value": 1 },
  "e0Hello1": { "name": "HELLO", "value": 1 },
  "e0Hello2": { "name": "HELLO", "value": 1 },
  "e0Hello3": { "name": "HELLO", "value": 1 }
}
```
now `type: t0` resolves to the "top" `t0`.

I get a feeling type name are global somehow even when using `::`?

**Comment by wader** [comment] 2023-04-11 10:10
Should mention that i'm experiment with adding basic runtime support for kaitai to https://github.com/wader/fq so i'm trying to get a deeper understanding how types, enums etc are namespaces and resolved.

**Comment by Mingun** [comment] 2023-04-11 11:11
There is a bug in WebIDE about equally named types: https://github.com/kaitai-io/kaitai_struct_webide/issues/105

**Comment by wader** [comment] 2023-04-11 15:48
@generalmimon Thanks! that was exactly what i was looking for, and will keep in mind to not trust it too much :) to be clear, by "probably follow intuitively" you mean it should be quite straight forward to extend the described algorithm to support paths?

In the 3rd step when it says
> 3. If that fails too, it goes one level up in the hierarchy of nested types and tries to resolve it there.

Should one only look one level up or continue for each parent down to the root? when i tested both type and enums seems to go all the way to the root:

```yaml
meta:
  id: enum_to_i
  endian: le
seq:
  - id: s
    type: a
enums:
  e:
    0x50: name
types:
  b:
    seq:
      - id: s
        type: u1
  a:
    types:
      a:
        types:
          a:
            seq:
              - id: s0
                type: b
              - id: s1
                type: u1
                enum: e

```
webide result:
```json
{
  "s": {
    "s0": {
      "s": 80
    },
    "s1": { "name": "NAME", "value": 75 }
  }
}
```

**Comment by generalmimon** [comment] 2023-04-11 16:13
@wader:

> In the 3rd step when it says
> 
> > 3. If that fails too, it goes one level up in the hierarchy of nested types and tries to resolve it there.
> 
> Should one only look one level up or continue for each parent down to the root? when i tested both type and enums seems to go all the way to the root:

Yes, step 3 is definitely meant to be recursive (i.e. the step 3 is actually "go back to step 1 and follow the process again, but now the _current type_ is the type one level up in the hierarchy).

**Comment by generalmimon** [comment] 2023-04-11 16:52
@wader:

> to be clear, by "probably follow intuitively" you mean it should be quite straight forward to extend the described algorithm to support paths?

Yes, only the first component of the type path has the special handling with fallbacks (it's the same handling as described [in the KSY reference](https://github.com/kaitai-io/kaitai_struct_doc/blob/88c32183b26e4d2265bfecdce0a3dfeaea6975ff/ksy_reference.adoc#type), i.e. the actual type resolved as `foo` in `type: foo` and `type: foo::{...}` is always the same). All subsequent components of the path should have no fallbacks.

I'm not sure whether examples in this case are not more confusing than helpful, but I'll try anyway.

```ksy
meta:
  id: nested_types_paths
seq:
  - id: abc
    type: a::b
types:
  a:
    seq: []
    types:
      b:
        seq:
          - id: obj_cd
            type: c::d
        types: {}

  c:
    seq: []
    types:
      d:
        seq:
          - id: d_attr
            type: s1
```

Notice the `obj_de` attribute in the `/types/a/types/b` type. It references a type `c::d`. Finding what specific type `c` refers to is non-trivial (and it's using the same algorithm as for plain `type: c`). First, you need to

1. check <code>/types/a/types/b/<ins><strong>types</strong></ins></code>, only to find that the `c` isn't defined there (in this case);
2. check if the current type (still `/types/a/types/b`) has the name `c`. It doesn't, so we're now moving to the type one level up in the nested types hierarchy (`/types/a`).

No luck finding the `c` type under `/types/a/types/b/` => the new "current type" is `/types/a`.

1. check <code>/types/a/<ins><strong>types</strong></ins></code> - nope, no `c` there;
2. check if the current type (`/types/a`) is `c`: it's not. We're moving to the top-level type, i.e. the YAML path `/` (in KS language, it can be referred to using the name in `/meta/id`, i.e. `nested_types_paths`).

Now searching in `/`:

1. check <code>/<ins><strong>types</strong></ins></code> - yes, we've finally found the definition of `c` in `/types/c`.

---

Now when you know what `type: c` corresponds to, <code>type: c::<ins><strong>d</strong></ins></code> is easy. Given that `type: c` has been resolved as `/types/c`, the only valid location for `type: c::d` is <code>/types/c/types/<ins><strong>d</strong></ins></code>. If `d` is not there, game over - the spec is invalid.

**Comment by wader** [comment] 2023-04-11 17:19
@generalmimon Thanks! much appreciated with nice example. Don't think i would gotten all those details right by testing things.

Another thing: Is the types and enums namespace shared for a type? I tried having a type and enum with the same name and the type seems to shadow/override the enum in webide. When i tried with ksdump the generated ruby fails with:

```
meta:
  id: type_enum_collision
seq:
  - id: s0
    type: e

types:
  e:
    seq:
      - id: a
        type: u1
        enum: e

enums:
  e:
    0: name
```
```
type_enum_collision.rb:29:in `<class:TypeEnumCollision>': E is not a class (TypeError)
ype_enum_collision.rb:12: previous definition of E was here
```

Hope it's ok with all questions. Maybe some of it could be used to clarify documentation?

If you want to follow the progress in fq the issue is https://github.com/wader/fq/issues/627

No code has been pushed yet but current progress is that i have a quite complete expression language parser/evaluator that passes most of the tests i've found, somewhat working ksy schema parser, kaitai style "bit-endian" integer kind-of works. The biggest mess currently it the code to glue it all together with the fq decode "DSL", and that also depend quite a lot on how types are resolved etc.  But it's looking promising i think, some days ago mp4.ksy and png.ksy produced a somewhat good looking decode tree :)

**Comment by wader** [comment] 2023-04-14 14:32
Thanks again, will help a lot! Should we keep this issue open or close it? guess i will probably run into more questions around types but could maybe open new issues if this was specific to resolving.

**Closed** 2023-04-14 15:34 UTC
Labels: question

**Comment by generalmimon** [comment] 2023-04-23 08:57
@wader For the sake of completeness of this issue, I've nearly forgotten that there are in fact various verbose modes of KSC available via the `--verbose` option which allow you to see how some parts of KSC operate, see [`Log.scala:43-57`](https://github.com/kaitai-io/kaitai_struct_compiler/blob/829a14f1e33e8e48eeae726c8a287a5967bcb668/shared/src/main/scala/io/kaitai/struct/Log.scala#L43-L57). For detailed info from the component responsible for resolving types, there is `--verbose type_resolve` (or you can use `--verbose all` which will log everything):

```console
$ kaitai-struct-compiler-0.10 -- --verbose type_resolve -t java nested_types_paths.ksy
resolveUserType: at List(nested_types_paths) doing a|b
resolveUserType: at List(nested_types_paths, a) doing b
    => nested_types_paths::a::b
    => nested_types_paths::a::b
resolveUserType: at List(nested_types_paths, a, b) doing c|d
resolveUserType: at List(nested_types_paths, a) doing c|d
resolveUserType: at List(nested_types_paths) doing c|d
resolveUserType: at List(nested_types_paths, c) doing d
    => nested_types_paths::c::d
    => nested_types_paths::c::d
    => nested_types_paths::c::d
    => nested_types_paths::c::d
```

**Comment by wader** [comment] 2023-04-23 09:48
@generalmimon Thanks that is good know. Been away traveling this weekend but back now and hope i get some time this week to work on it.

**Comment by generalmimon** [comment] 2023-04-23 09:52
Hmm, seeing the verbose output made me worried that when resolving the type path `c::d`, the compiler uses the same complex algorithm to resolve `d` starting from `c` (and not just a simple lookup whether there is a direct subtype called `d` in <code>/types/c/types/<ins><strong>d</strong></ins></code>):

<pre><code>resolveUserType: at List(nested_types_paths, a, b) doing c|d
resolveUserType: at List(nested_types_paths, a) doing c|d
resolveUserType: at List(nested_types_paths) doing c|d
<ins><strong>resolveUserType: at List(nested_types_paths, c) doing d</strong></ins></code></pre>

And my worries were unfortunately confirmed - this is "happily" compiled by KSC, even though the `c::d` type reference should be flagged as invalid (since `c` has no subtype `d`):

```ksy
meta:
  id: nested_types_paths
seq:
  - id: obj_a
    type: a
types:
  a:
    seq:
      - id: obj_cd
        type: nested_types_paths::c::d

  c:
    seq: []
    # types:
    #   d:
    #     seq:
    #       - id: d_attr
    #         type: s1
  d:
    seq:
      - id: d_attr
        type: s1
```

Parsers generated from this spec don't seem to work in any language (which is not surprising - the spec above shouldn't be allowed to compile in the first place). In JavaScript (via the [Web IDE](https://ide.kaitai.io/)) an error is thrown:

```
Parse error (TypeError): NestedTypesPaths.C.D is not a constructor
Call stack: TypeError: NestedTypesPaths.C.D is not a constructor
    at NestedTypesPaths.A.A._read (eval at initCode (https://ide.kaitai.io/js/v1/kaitaiWorker.js:89:9), <anonymous>:37:20)
    at NestedTypesPaths._read (eval at initCode (https://ide.kaitai.io/js/v1/kaitaiWorker.js:89:9), <anonymous>:23:15)
    at reparse (https://ide.kaitai.io/js/v1/kaitaiWorker.js:96:17)
    at myself.onmessage (https://ide.kaitai.io/js/v1/kaitaiWorker.js:117:47)
```

and the generated Java code doesn't compile:

```console
$ shopt -s globstar

$ javac -encoding 'UTF-8' /c/temp/kaitai_struct/runtime/java/**/*.java NestedTypesPaths.java
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding="UTF-8"
NestedTypesPaths.java:52: error: cannot find symbol
        private NestedTypesPaths.C.D objCd;
                                  ^
  symbol:   class D
  location: class C
NestedTypesPaths.java:55: error: cannot find symbol
        public NestedTypesPaths.C.D objCd() { return objCd; }
                                 ^
  symbol:   class D
  location: class C
NestedTypesPaths.java:50: error: cannot find symbol
            this.objCd = new NestedTypesPaths.C.D(this._io);
                                               ^
  symbol:   class D
  location: class C
3 errors
```

Which all confirms that it really shouldn't be accepted, and the fact that KSC does is a bug.
