### ISSUE TITLE
cases causing type inference interference

### ISSUE THREAD

**Issue by webbnh** [kaitai-io/kaitai_struct#414] opened 2018-04-10 02:01 UTC
The following KSY represents the current state of my project:
```ksy
enums:
  rec_types:
    1: fileheader
    2: filetrailer
    3: data
meta:
  endian: le
  id: kscbug
  title: Demonstrate a type inference bug
seq:
- id: fileheader
  type: fileheader
- doc: Having this reference satisfies type deduction requirements; the conditional
    allows us to defer reading it.
  id: records
  if: false
  type: record
types:
  record:
    seq:
    - id: type
      type: u1
    - id: length
      type: u1
    - id: payload
      type:
        cases:
          0x39: filemiddlething  # Remove this line for "empty.reduceLeft" error
          _:    payload_bytes
        switch-on: type
    - id: trailer
      type: u1
      if: type != 0x39 and type != 0xff
  payload_bytes:
    doc:  This is a place-holder type -- if we reference the "payload" type directly, then we lose lazy evaluation.
    seq:
      - size: _parent.length
  payload:
    params:
    - doc: receive the type as an int to work around a bug in KSC V0.8
      id: rec_type_int
      type: u1
    instances:
      rec_type:
        doc:  convert the int to the proper enum for the switch
        value: rec_type_int
        enum: rec_types
    seq:
    - id: data
      type:
        cases:
          rec_types::data: data
          rec_types::fileheader: fileheader
          rec_types::filetrailer: filetrailer
        switch-on: rec_type
  fileheader:
    seq:
    - id: fmt
      type: u4
  filetrailer:
    seq:
    - id: cnt
      type: u4
  filemiddlething:
    seq:
    - size: 2
  data:
    seq:
    - id: fld
      type: u4
```
Unfortunately, the C++ code which KSC generates for it doesn't compile:
```console
$ ksc -t cpp_stl --outdir ~/tmp ~/tmp/kscbug3.ksy 
$ c++ -c -I/opt/kaitai_struct_cpp_stl_runtime kscbug.cpp 
kscbug.cpp:47:22: error: no matching constructor for initialization of
      'kscbug_t::fileheader_t'
        m_data = new fileheader_t(m__io, this, m__root);
                     ^            ~~~~~~~~~~~~~~~~~~~~
./kscbug.h:139:9: note: candidate constructor not viable: no known conversion
      from 'kscbug_t::payload_t *' to 'kscbug_t *' for 2nd argument
        fileheader_t(kaitai::kstream* p__io, kscbug_t* p__parent = 0, ks...
        ^
./kscbug.h:135:11: note: candidate constructor (the implicit copy constructor)
      not viable: requires 1 argument, but 3 were provided
    class fileheader_t : public kaitai::kstruct {
          ^
kscbug.cpp:152:21: error: assigning to 'kscbug_t::filemiddlething_t *' from
      incompatible type 'kscbug_t::payload_bytes_t *'
        m_payload = new payload_bytes_t(m__io, this, m__root);
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
```

It looks like something in the first `cases` map is interfering with the type inference for `fileheader` (which is referenced both from the main `seq` and from the `payload` type, which have no type in common) such that it gets declared expecting a `kscbug_t` as a parent instead of a `kaitai::kstruct` (which causes problems for the `payload_t` type).  

Strangely, `data_t` and `filetrailer_t` don't seem to get the proper parent -- they are expecting a `kaitai::kstruct` when I think they should be expecting a `payload_t`.

And then, for whatever reason, `filemiddlething_t` is (properly) expecting a `record_t` but it's being handed a `payload_bytes_t`.

**Comment by KOLANICH** [comment] 2018-04-10 05:57
@webbnh Thank you for the report and please keep in mind that C++ target is not production-ready. C++ is not a memory-safe language and if I remember right there were no security audit of C++ support in compiler and runtime. You may want to generate the parser in rust and use it via FFI instead.

**Comment by GreyCat** [comment] 2018-04-10 09:58
@KOLANICH Please stop spreading this bullshit.

> C++ target is not production-ready.

C++/STL target is used by several dozens of projects in production, and is supported on par of most other languages in KS (~98% tests pass).

> there were no security audit of C++ support in compiler and runtime

There is valgrind that runs regularly in CI on C++ tests. There is a known memory leak, but it is only related to exceptions. If a parser run normally does not throw exceptions (or that exception would be fatal anyway), then it shouldn't be a concern.

> You may want to generate the parser in rust and use it via FFI instead.

Rust target is not even at the CI and master branch right now. Very mature, yeah.

**Comment by webbnh** [comment] 2018-07-18 20:44
> There is a known memory leak, but it is only related to exceptions.
Would that be related to the fact that the generated `_read()` method calls `new()` twice during a call from a constructor, with the second invoking a constructor which itself calls `_read()`, such that, if the read fails, the resulting exception goes unhandled and the allocation from the first call to `new()` never gets deleted?

Yup, I just noticed that.  :-/  Unfortunately, my test run hit that particular wrinkle 30,000 times, leaking 9.5Mb of memory.

Ah...I just found #214...I'll go reply there.

**Comment by smx-smx** [comment] 2024-03-13 00:06
I don't think this error is related to `cases`.
The following simple `ksy` file causes the same issue on the latest git `HEAD`

```yaml
meta:
  id: ksy_issue
  file-extension: ksy_issue
  endian: le
types:
  shared:
    seq:
      - id: hello
        type: u4
  type1:
    seq: 
      - id: val
        type: shared
  type2:
    seq: 
      - id: val
        type: shared
seq:
  - id: item
    type: type1
```

output from
```
kaitai-struct-compiler --target cpp_stl ksy_issue.ksy && \
g++ \
-DKS_STR_ENCODING_ICONV \
-I kaitai_struct_cpp_stl_runtime \
ksy_issue.cpp kaitai_struct_cpp_stl_runtime/kaitai/*.cpp \
-shared
```

```
ksy_issue.cpp: In member function ‘void ksy_issue_t::type2_t::_read()’:
ksy_issue.cpp:96:46: error: no matching function for call to ‘ksy_issue_t::shared_t::shared_t(kaitai::kstream*&, ksy_issue_t::type2_t*, ksy_issue_t*&)’
   96 |     m_val = new shared_t(m__io, this, m__root);
      |                                              ^
ksy_issue.cpp:32:1: note: candidate: ‘ksy_issue_t::shared_t::shared_t(kaitai::kstream*, ksy_issue_t::type1_t*, ksy_issue_t*)’
   32 | ksy_issue_t::shared_t::shared_t(kaitai::kstream* p__io, ksy_issue_t::type1_t* p__parent, ksy_issue_t* p__root) : kaitai::kstruct(p__io) {
      | ^~~~~~~~~~~
ksy_issue.cpp:32:79: note:   no known conversion for argument 2 from ‘ksy_issue_t::type2_t*’ to ‘ksy_issue_t::type1_t*’
   32 | ksy_issue_t::shared_t::shared_t(kaitai::kstream* p__io, ksy_issue_t::type1_t* p__parent, ksy_issue_t* p__root) : kaitai::kstruct(p__io) {
      |                                                         ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
In file included from ksy_issue.cpp:3:
ksy_issue.h:29:11: note: candidate: ‘constexpr ksy_issue_t::shared_t::shared_t(const ksy_issue_t::shared_t&)’
   29 |     class shared_t : public kaitai::kstruct {
      |           ^~~~~~~~
ksy_issue.h:29:11: note:   candidate expects 1 argument, 3 provided
```

The fix is to manually go in the generated file and change occurrences of `ksy_issue_t::type1_t*` with the base type `kaitai::kstruct*`

It seems that the compiler is failing to realize that the type is referenced (or otherwise included) by 2 different types, and it should fallback to the generic base type that is common to both.
In this particular case the type of `p__parent` is irrelevant, since the shared type doesn't use `_parent`.

This means that the following generated getter could also be omitted (along with `m__parent`), but I digress (it's not really an issue per se)
```
ksy_issue_t::type1_t* _parent() const { return m__parent; }
```

**Comment by Mingun** [comment] 2024-03-13 17:15
When fixing this it is also possible to fix #935, their roots are close in code to each other.

**Comment by Mingun** [comment] 2024-03-13 17:27
Actually, this is duplicate of #89

**Comment by generalmimon** [comment] 2024-03-14 15:06
Otherwise @Mingun is right, the primary problem demonstrated in this issue is the same as reported in #961. More specifically, the `payload` type in https://github.com/kaitai-io/kaitai_struct/issues/414#issue-312746847 is unreachable (unused) from root `seq` or `instances`, which means its usages of other types don't participate in derivation of their `_parent` types. The same goes for `type2` in https://github.com/kaitai-io/kaitai_struct/issues/414#issuecomment-1992771490.

However, since the problem is better explained in #961 than here, I'll close this issue in favor of #961 as duplicate.

**Closed** 2024-03-14 15:06 UTC
Labels: bug found, duplicate
