### ISSUE TITLE
[Question] Type Parameter

### ISSUE THREAD

**Issue by Dakota628** [kaitai-io/kaitai_struct#1045] opened 2023-07-07 16:48 UTC
Hi,

Is it possible for a user type to take other types as a parameter? This functionality would be similar to generics in some languages. For example, consider the below "optional" type:

```yaml
dt_null:
  doc: Intentionally left empty
dt_optional:
  params:
    - id: t
      type: type # This doesn't currently exist, for example purposes only
  seq:
    - id: exists
      type: s4le
    - id: value
      type:
        cases:
          0: dt_null
          _: t
        switch-on: exists
example_type_using_optional:
  - id: foo
    type: dt_optional(dt_vector4d)
  - id: bar
    type: dt_optional(dt_arbitrary_large_type)
```

**Comment by GreyCat** [comment] 2023-07-10 08:33
See #135 — you're completely correct that it's not available right now, and it's requested quite often. However, implementation is fairly difficult and nobody seems to have tackled it yet.

**Comment by GreyCat** [comment] 2023-07-10 08:33
Duplicate of #135

**Closed by GreyCat** 2023-07-10 08:33 UTC
