### ISSUE TITLE
Referencing an enum of an imported spec doesn't work in some languages

### ISSUE THREAD

**Issue by eric-corumdigital** [kaitai-io/kaitai_struct#651] opened 2019-12-09 18:46 UTC
OS: Windows
KSC: kaitai-struct-compiler 0.9-SNAPSHOT

my_enum.ksy
```ksy
meta:
  id: my_enum

enums:
  t:
    0: x
```

my_type.ksy
```ksy
meta:
  id: my_type
  imports:
    - my_enum

seq:
  - id: my_field
    type: u1
    enum: my_enum::t
```

```
>kaitai-struct-compiler -t javascript my_type.ksy
/seq/0: unable to find enum 'my_enum::t', searching from my_type
```

**Comment by GreyCat** [comment] 2019-12-09 19:30
Initial solution seems to be checked in, along with the [test that reproduces the problem](https://github.com/kaitai-io/kaitai_struct_tests/blob/master/formats/enum_import.ksy). Unfortunately, it's still not a solution, as it looks like different languages have some other problems in adoption of such constructs. Only Ruby seems to pass so far.

**Comment by generalmimon** [comment] 2024-04-15 22:05
This has been resolved recently. The relevant test is called `EnumImportSeq` (previously just `EnumImport`). Check the [CI dashboard](https://ci.kaitai.io/) - this test now passes in all targets except Construct (which doesn't support `imports` yet; https://github.com/kaitai-io/kaitai_struct_compiler/pull/242 apparently attempts to add it).

The main general problem was that the compiler didn't generate imports for imported enums. This was solved in commit https://github.com/kaitai-io/kaitai_struct_compiler/commit/bb532050c90247c1a52bb775de7b40982c3c8db6, which fixed `EnumImportSeq` for C++ and Perl. In Python, references to external enums were also incorrect, which was fixed in commit https://github.com/kaitai-io/kaitai_struct_compiler/commit/e4aebb88db9c62528c048a279c78a26e88e333c5.

**Closed by generalmimon** 2024-04-15 22:05 UTC
Labels: bug found
