### ISSUE TITLE
GIF example on homepage does not work

### ISSUE THREAD

**Issue by Picoseconds** [kaitai-io/kaitai_struct#893] opened 2021-07-15 22:07 UTC
**Steps to reproduce:**
Try and compile the GIF example for C#
Fail with error
```cs
main.cs(96,23): error CS0102: The type `ConsoleApp1.Gif' already contains a definition for `Header'
main.cs(25,30): (Location of the symbol related to previous error)
main.cs(97,30): error CS0102: The type `ConsoleApp1.Gif' already contains a definition for `LogicalScreen'
main.cs(56,30): (Location of the symbol related to previous error)
Compilation failed: 2 error(s), 0 warnings
```

The class for the header type and the getter for the header property in seq conflict

**Comment by generalmimon** [comment] 2021-07-16 11:18
This is an instance of https://github.com/kaitai-io/kaitai_struct/issues/86. The temporary workaround is to name all `seq` fields, `instances`, user-defined types and enums differently.

Closing as duplicate of https://github.com/kaitai-io/kaitai_struct/issues/86. Please continue the discussion there if you have any remarks that haven't been mentioned yet.

**Closed by generalmimon** 2021-07-16 11:18 UTC
