### ISSUE TITLE
Error messages doen't have line number

### ISSUE THREAD

**Issue by Mingun** [kaitai-io/kaitai_struct#669] opened 2020-01-10 09:06 UTC
When `ksc` produces error it won't tell in what line it is originated.

Also, most errors are very obscure

**Comment by generalmimon** [comment] 2020-01-10 23:24
> When `ksc` produces error it won't tell in what line it is originated.

The problem is that the Kaitai Struct compiler uses external YAML libraries to parse .ksy files, it has no innate knowledge of the individual characters or lines. Instead, it gets the YAML tree and deals with its sequences or maps.

It's easier to work with it, the disadvantage is that we lose knowledge of the current position in the file, cannot affect the way YAML parsers deal with string literals containing `:` (in some environments, it's possible to leave them unquoted, in others not), how they treat numbers (sometimes, it can cause some weird bugs like https://github.com/kaitai-io/kaitai_struct/issues/456) etc.

There is a proposal of developing our own YAML parser (#229), that would open up a lot of possibilites, but unfortunately it doesn't seem to have made much progress.

> Also, most errors are very obscure

Any chance you could improve them in the KSC to make them more readable? My tip is, clone the [compiler repo](https://github.com/kaitai-io/kaitai_struct_compiler) and do fulltext search for regex `(Error|Exception)\(s"`, it should reveal the vast majority of the messages used in the compiler. Any help is appreciated.

**Comment by dgelessus** [comment] 2020-01-11 14:44
> My tip is, clone the [compiler repo](https://github.com/kaitai-io/kaitai_struct_compiler) and do fulltext search for regex `(Error|Exception)\(s"`, it should reveal the vast majority of the messages used in the compiler.

Unfortunately not all exceptions that the user sees are explicitly thrown by ksc. Sometimes they come from the Scala runtime, for example `None.get` or pattern matching errors. These are very difficult to understand, especially if you're not familiar with ksc internals.

**Comment by GreyCat** [comment] 2020-01-11 18:24
Scala runtime exceptions are not considered a normal flow. These are internal compiler errors, and we strive to fix them all.

**Comment by Mingun** [comment] 2020-01-12 16:03
> Also, most errors are very obscure

One of such errors. When trying to parse such `ksy`:
```yaml
meta:
  id: bug
params:
  - id: param
    type: b1
seq: []
```
compiler throws error
```
Exception in thread "main" scala.MatchError: b1 (of class java.lang.String)
	at io.kaitai.struct.datatype.DataType$.pureFromString(DataType.scala:322)
	at io.kaitai.struct.format.ParamDefSpec$.fromYaml(ParamDefSpec.scala:32)
	at io.kaitai.struct.format.ParamDefSpec$.fromYaml(ParamDefSpec.scala:19)
	at io.kaitai.struct.format.ClassSpec$$anonfun$3.apply(ClassSpec.scala:140)
	at io.kaitai.struct.format.ClassSpec$$anonfun$3.apply(ClassSpec.scala:139)
	at scala.collection.immutable.List.map(List.scala:284)
	at io.kaitai.struct.format.ClassSpec$.paramDefFromYaml(ClassSpec.scala:139)
	at io.kaitai.struct.format.ClassSpec$.fromYaml(ClassSpec.scala:95)
	at io.kaitai.struct.format.ClassSpec$.fromYaml(ClassSpec.scala:224)
	at io.kaitai.struct.formats.JavaKSYParser$.fileNameToSpec(JavaKSYParser.scala:29)
	at io.kaitai.struct.formats.JavaKSYParser.fileNameToSpec(JavaKSYParser.scala)
	at io.kaitai.struct.visualizer.VisualizerPanel.compileKSY(VisualizerPanel.java:89)
	at io.kaitai.struct.visualizer.VisualizerPanel.parseFileWithKSY(VisualizerPanel.java:125)
	at io.kaitai.struct.visualizer.VisualizerPanel.loadAll(VisualizerPanel.java:67)
	at io.kaitai.struct.visualizer.MainWindow.main(MainWindow.java:24)
```

**Comment by GreyCat** [comment] 2020-01-20 14:31
As @generalmimon has mentioned, it's a known and long ongoing problem and we have a task to use better / create our own YAML parser at #229. Outside of that, there's nothing we can really do to track errors to line numbers  — currently, we do our best to pinpoint the YAML path, if that's possible.

All internal errors like above should be posted as separate issues to track — I've split this one, for example, into #684. Thanks for reporting it.

I'll be closing this one as it will likely be better tracked in #229. Let's continue the discussion there?

**Closed by GreyCat** 2020-01-20 14:31 UTC
