### ISSUE TITLE
Switch fall-through

### ISSUE THREAD

**Issue by Ralle** [kaitai-io/kaitai_struct#638] opened 2019-10-18 15:03 UTC
When I use switch statements, I kind of want to express that only the options in the switch are allowed. In case of anything else, I want kaitat to throw an exception.
This could be expressed this way:
`_: error`

**Comment by KOLANICH** [comment] 2019-10-18 18:57
#435 #81

**Comment by Ralle** [comment] 2019-10-20 17:56
I did my searching but your issues just let me find an exact match: #208

**Comment by GreyCat** [comment] 2019-10-20 19:40
@Ralle Thanks for sorting this one, I'll mark this one as duplicate of #208.

**Closed by GreyCat** 2019-10-20 19:40 UTC
