### ISSUE TITLE
an implementation is missing: kaitai-struct-compiler golang

### ISSUE THREAD

**Issue by atikj** [kaitai-io/kaitai_struct#1134] opened 2024-10-04 11:20 UTC
I am getting below exception when below command is executed.

`
AD001@abc WW64 /c/ABC/REPOS/XYZ/aep/resources (patch-br)
$ kaitai-struct-compiler --debug --ksc-exceptions -t=go --go-package=etcs --outdir ./etnew_all diagfile_all.ksy

scala.NotImplementedError: an implementation is missing
        at scala.Predef$.$qmark$qmark$qmark(Predef.scala:288)
        at io.kaitai.struct.translators.GoTranslator.doCast(GoTranslator.scala:275)
        at io.kaitai.struct.translators.GoTranslator.doCast(GoTranslator.scala:18)
        at io.kaitai.struct.translators.CommonArraysAndCast.doCastOrArray(CommonArraysAndCast.scala:71)
        at io.kaitai.struct.translators.CommonArraysAndCast.doCastOrArray$(CommonArraysAndCast.scala:53)
        at io.kaitai.struct.translators.GoTranslator.doCastOrArray(GoTranslator.scala:18)
        at io.kaitai.struct.translators.GoTranslator.translateExpr(GoTranslator.scala:111)
        at io.kaitai.struct.translators.GoTranslator.translate(GoTranslator.scala:31)
        at io.kaitai.struct.translators.CommonOps.numericBinOp(CommonOps.scala:7)
        at io.kaitai.struct.translators.CommonOps.numericBinOp$(CommonOps.scala:6)
        at io.kaitai.struct.translators.GoTranslator.numericBinOp(GoTranslator.scala:18)
        at io.kaitai.struct.translators.GoTranslator.trNumericBinOp(GoTranslator.scala:154)
        at io.kaitai.struct.translators.GoTranslator.translateExpr(GoTranslator.scala:92)
        at io.kaitai.struct.translators.GoTranslator.translate(GoTranslator.scala:31)
        at io.kaitai.struct.translators.CommonOps.numericBinOp(CommonOps.scala:7)
        at io.kaitai.struct.translators.CommonOps.numericBinOp$(CommonOps.scala:6)
        at io.kaitai.struct.translators.GoTranslator.numericBinOp(GoTranslator.scala:18)
        at io.kaitai.struct.translators.GoTranslator.trNumericBinOp(GoTranslator.scala:154)
        at io.kaitai.struct.translators.GoTranslator.translateExpr(GoTranslator.scala:92)
        at io.kaitai.struct.translators.GoTranslator.translate(GoTranslator.scala:31)
        at io.kaitai.struct.translators.GoTranslator.$anonfun$userType$1(GoTranslator.scala:470)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:285)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at scala.collection.TraversableLike.map(TraversableLike.scala:285)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:278)
        at scala.collection.AbstractTraversable.map(Traversable.scala:108)
        at io.kaitai.struct.translators.GoTranslator.userType(GoTranslator.scala:470)
        at io.kaitai.struct.languages.components.GoReads.attrUserTypeParse(GoReads.scala:137)
        at io.kaitai.struct.languages.components.GoReads.attrUserTypeParse$(GoReads.scala:112)
        at io.kaitai.struct.languages.GoCompiler.attrUserTypeParse(GoCompiler.scala:11)
        at io.kaitai.struct.languages.components.GoReads.attrParse2(GoReads.scala:62)
        at io.kaitai.struct.languages.components.GoReads.attrParse2$(GoReads.scala:51)
        at io.kaitai.struct.languages.GoCompiler.attrParse2(GoCompiler.scala:11)
        at io.kaitai.struct.languages.components.GoReads.$anonfun$attrSwitchTypeParse$2(GoReads.scala:46)
        at io.kaitai.struct.languages.components.GoReads.$anonfun$attrSwitchTypeParse$2$adapted(GoReads.scala:42)
        at io.kaitai.struct.languages.components.SwitchOps.$anonfun$switchCasesRender$3(SwitchOps.scala:89)
        at io.kaitai.struct.languages.components.SwitchOps.$anonfun$switchCasesRender$3$adapted(SwitchOps.scala:87)
        at scala.Option.foreach(Option.scala:407)
        at io.kaitai.struct.languages.components.SwitchOps.switchCasesRender(SwitchOps.scala:87)
        at io.kaitai.struct.languages.components.SwitchOps.switchCasesRender$(SwitchOps.scala:53)
        at io.kaitai.struct.languages.components.LanguageCompiler.switchCasesRender(LanguageCompiler.scala:11)
        at io.kaitai.struct.languages.components.GoSwitchOps.switchCases(GoSwitchOps.scala:27)
        at io.kaitai.struct.languages.components.GoSwitchOps.switchCases$(GoSwitchOps.scala:15)
        at io.kaitai.struct.languages.GoCompiler.switchCases(GoCompiler.scala:11)
        at io.kaitai.struct.languages.components.GoReads.attrSwitchTypeParse(GoReads.scala:42)
        at io.kaitai.struct.languages.components.GoReads.attrSwitchTypeParse$(GoReads.scala:28)
        at io.kaitai.struct.languages.GoCompiler.attrSwitchTypeParse(GoCompiler.scala:11)
        at io.kaitai.struct.languages.components.GoReads.attrParse2(GoReads.scala:66)
        at io.kaitai.struct.languages.components.GoReads.attrParse2$(GoReads.scala:51)
        at io.kaitai.struct.languages.GoCompiler.attrParse2(GoCompiler.scala:11)
        at io.kaitai.struct.languages.components.CommonReads.attrParse0(CommonReads.scala:77)
        at io.kaitai.struct.languages.components.CommonReads.attrParse0$(CommonReads.scala:65)
        at io.kaitai.struct.languages.GoCompiler.attrParse0(GoCompiler.scala:11)
        at io.kaitai.struct.languages.components.CommonReads.attrParse(CommonReads.scala:39)
        at io.kaitai.struct.languages.components.CommonReads.attrParse$(CommonReads.scala:9)
        at io.kaitai.struct.languages.GoCompiler.attrParse(GoCompiler.scala:11)
        at io.kaitai.struct.ClassCompiler.$anonfun$compileSeq$1(ClassCompiler.scala:296)
        at io.kaitai.struct.ClassCompiler.$anonfun$compileSeq$1$adapted(ClassCompiler.scala:292)
        at scala.collection.immutable.List.foreach(List.scala:431)
        at io.kaitai.struct.ClassCompiler.compileSeq(ClassCompiler.scala:292)
        at io.kaitai.struct.ClassCompiler.compileSeqProc(ClassCompiler.scala:281)
        at io.kaitai.struct.ClassCompiler.compileEagerRead(ClassCompiler.scala:239)
        at io.kaitai.struct.GoClassCompiler.compileReadFunction(GoClassCompiler.scala:58)
        at io.kaitai.struct.GoClassCompiler.compileClass(GoClassCompiler.scala:40)
        at io.kaitai.struct.ClassCompiler.$anonfun$compileSubclasses$1(ClassCompiler.scala:313)
        at io.kaitai.struct.ClassCompiler.$anonfun$compileSubclasses$1$adapted(ClassCompiler.scala:313)
        at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:394)
        at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:721)
        at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:721)
        at io.kaitai.struct.ClassCompiler.compileSubclasses(ClassCompiler.scala:313)
        at io.kaitai.struct.GoClassCompiler.compileClass(GoClassCompiler.scala:47)
        at io.kaitai.struct.ClassCompiler.compile(ClassCompiler.scala:23)
        at io.kaitai.struct.Main$.compile(Main.scala:101)
        at io.kaitai.struct.JavaMain.compileSpecAndWriteToFile(JavaMain.scala:361)
        at io.kaitai.struct.JavaMain.$anonfun$compileOneLang$2(JavaMain.scala:339)
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:285)
        at scala.collection.mutable.HashMap.$anonfun$foreach$1(HashMap.scala:149)
        at scala.collection.mutable.HashTable.foreachEntry(HashTable.scala:237)
        at scala.collection.mutable.HashTable.foreachEntry$(HashTable.scala:230)
        at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:44)
        at scala.collection.mutable.HashMap.foreach(HashMap.scala:149)
        at scala.collection.TraversableLike.map(TraversableLike.scala:285)
        at scala.collection.TraversableLike.map$(TraversableLike.scala:278)
        at scala.collection.AbstractTraversable.map(Traversable.scala:108)
        at io.kaitai.struct.JavaMain.compileOneLang(JavaMain.scala:337)
        at io.kaitai.struct.JavaMain.compileOneInput(JavaMain.scala:298)
        at io.kaitai.struct.JavaMain.$anonfun$run$1(JavaMain.scala:258)
        at scala.collection.immutable.List.map(List.scala:293)
        at io.kaitai.struct.JavaMain.run(JavaMain.scala:256)
        at io.kaitai.struct.JavaMain$.main(JavaMain.scala:247)
        at io.kaitai.struct.JavaMain.main(JavaMain.scala)
maintdiagfile: /:
        error: an implementation is missing
`
If we use the same ksy file on KaitaiWebIDE, it worked but during kaitai-struct-compiler command execution it fails.
How to fix this issue?

**Comment by generalmimon** [comment] 2024-10-04 15:43
Duplicate of https://github.com/kaitai-io/kaitai_struct/issues/931

**Closed by generalmimon** 2024-10-04 15:43 UTC
Labels: bug found, duplicate

**Comment by generalmimon** [comment] 2024-10-04 15:47
@atikj:

> If we use the same ksy file on KaitaiWebIDE, it worked but during kaitai-struct-compiler command execution it fails.
> How to fix this issue?

As already tracked in https://github.com/kaitai-io/kaitai_struct/issues/931, the problem is that the type cast operator (`.as<...>`) is not yet implemented for Go. You can fix the issue by avoiding `.as<...>` in your .ksy file.
