### ISSUE TITLE
Style guide missing pad-right

### ISSUE THREAD

**Issue by arekbulski** [kaitai-io/kaitai_struct#388] opened 2018-03-22 22:43 UTC
On the style guide, there is no pad-right?
http://doc.kaitai.io/ksy_style_guide.html#seq-attr

**Comment by cugu** [comment] 2018-04-01 22:18
Duplicate of #152

**Comment by GreyCat** [comment] 2018-04-02 13:42
Hmm, actually not exactly. This one is about "style guide", #152 is about "user guide", but I agree that both still need to be fixed...

**Comment by arekbulski** [comment] 2018-04-06 22:53
If you would just tell me where in that list it should be, and I will add it.

**Comment by arekbulski** [comment] 2018-04-07 16:28
I will update the docs and solve this issue.

**Comment by GreyCat** [comment] 2019-03-25 23:46
Added `pad-right`, closing this issue.

**Closed by GreyCat** 2019-03-25 23:46 UTC
Labels: bug found, documentation
