### ISSUE TITLE
Problem using parent type casting in switch cases

### ISSUE THREAD

**Issue by mickdekkers** [kaitai-io/kaitai_struct#200] opened 2017-07-06 10:15 UTC
Here's a minimum repro ksy:
```yaml
# Checks <insert description here>
meta:
  id: nav_parent_switch_cast
seq:
  - id: foo
    type: foo
types:
  foo:
    seq:
      - id: buf_type
        type: u1
      - id: flag
        type: u1
      - id: buf
        size: 4
        type:
          switch-on: buf_type
          cases:
            0: zero
            1: one
    types:
      zero:
        seq:
        - id: bar
          type: bar
      one:
        seq:
        - id: bar
          type: bar
      bar:
        instances:
          flag:
            value: '_parent._parent.as<foo>.flag'
```

You can test it with this data:
```
00 00 39 05 00 00
```

It currently throws this error:
```
scala.MatchError: KaitaiStructType (of class io.kaitai.struct.datatype.DataType$KaitaiStructType$)
        at io.kaitai.struct.translators.BaseTranslator.translate(BaseTranslator.scala:85)
        at io.kaitai.struct.translators.BaseTranslator.doCast(BaseTranslator.scala:164)
        at io.kaitai.struct.translators.BaseTranslator.translate(BaseTranslator.scala:158)
        at io.kaitai.struct.translators.BaseTranslator.userTypeField(BaseTranslator.scala:172)
        at io.kaitai.struct.translators.BaseTranslator.translate(BaseTranslator.scala:87)
        at io.kaitai.struct.languages.components.ObjectOrientedLanguage$class.expression(ObjectOrientedLanguage.scala:9)
        at io.kaitai.struct.languages.JavaScriptCompiler.expression(JavaScriptCompiler.scala:12)
        at io.kaitai.struct.languages.components.EveryReadIsExpression$class.instanceCalculate(EveryReadIsExpression.scala:185)
        at io.kaitai.struct.languages.JavaScriptCompiler.instanceCalculate(JavaScriptCompiler.scala:12)
        at io.kaitai.struct.ClassCompiler.compileInstance(ClassCompiler.scala:196)
        at io.kaitai.struct.ClassCompiler$$anonfun$compileInstances$1.apply(ClassCompiler.scala:176)
        at io.kaitai.struct.ClassCompiler$$anonfun$compileInstances$1.apply(ClassCompiler.scala:175)
        at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
        at io.kaitai.struct.ClassCompiler.compileInstances(ClassCompiler.scala:175)
        at io.kaitai.struct.ClassCompiler.compileClass(ClassCompiler.scala:82)
        at io.kaitai.struct.ClassCompiler$$anonfun$compileSubclasses$1.apply(ClassCompiler.scala:172)
        at io.kaitai.struct.ClassCompiler$$anonfun$compileSubclasses$1.apply(ClassCompiler.scala:172)
        at scala.collection.immutable.Map$Map3.foreach(Map.scala:161)
        at io.kaitai.struct.ClassCompiler.compileSubclasses(ClassCompiler.scala:172)
        at io.kaitai.struct.ClassCompiler.compileClass(ClassCompiler.scala:77)
        at io.kaitai.struct.ClassCompiler$$anonfun$compileSubclasses$1.apply(ClassCompiler.scala:172)
        at io.kaitai.struct.ClassCompiler$$anonfun$compileSubclasses$1.apply(ClassCompiler.scala:172)
        at scala.collection.immutable.Map$Map1.foreach(Map.scala:116)
        at io.kaitai.struct.ClassCompiler.compileSubclasses(ClassCompiler.scala:172)
        at io.kaitai.struct.ClassCompiler.compileClass(ClassCompiler.scala:77)
        at io.kaitai.struct.ClassCompiler.compile(ClassCompiler.scala:24)
        at io.kaitai.struct.Main$.compile(Main.scala:63)
        at io.kaitai.struct.JavaMain.compileSpecAndWriteToFile(JavaMain.scala:281)
        at io.kaitai.struct.JavaMain$$anonfun$compileOneLang$2.apply(JavaMain.scala:265)
        at io.kaitai.struct.JavaMain$$anonfun$compileOneLang$2.apply(JavaMain.scala:263)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:130)
        at scala.collection.mutable.HashMap$$anonfun$foreach$1.apply(HashMap.scala:130)
        at scala.collection.mutable.HashTable$class.foreachEntry(HashTable.scala:236)
        at scala.collection.mutable.HashMap.foreachEntry(HashMap.scala:40)
        at scala.collection.mutable.HashMap.foreach(HashMap.scala:130)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.AbstractTraversable.map(Traversable.scala:104)
        at io.kaitai.struct.JavaMain.compileOneLang(JavaMain.scala:263)
        at io.kaitai.struct.JavaMain.io$kaitai$struct$JavaMain$$compileOneInput(JavaMain.scala:242)
        at io.kaitai.struct.JavaMain$$anonfun$18.apply(JavaMain.scala:212)
        at io.kaitai.struct.JavaMain$$anonfun$18.apply(JavaMain.scala:210)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
        at scala.collection.immutable.List.map(List.scala:296)
        at io.kaitai.struct.JavaMain.run(JavaMain.scala:210)
        at io.kaitai.struct.JavaMain$.main(JavaMain.scala:201)
        at io.kaitai.struct.JavaMain.main(JavaMain.scala)
KaitaiStructType (of class io.kaitai.struct.datatype.DataType$KaitaiStructType$)
```

**Comment by generalmimon** [comment] 2019-11-24 22:06
This isn't exactly caused by casting, problem already happens on:
```yaml
bar:
  instances:
    flag:
      value: '_parent._parent'
```
It throws `/types/foo/types/bar/instances/flag/value: don't know how to call method '_parent' of object type 'KaitaiStructType'`. This is because combined parent type of _bar_ is `KaitaiStructType` (because both _zero_ and _one_ can be its parents) and that type doesn't allow any methods to be called on it (see [TypeDetector.scala](https://github.com/kaitai-io/kaitai_struct_compiler/blob/011feaeef8760e725d6b6c8568bc510205f4e79a/shared/src/main/scala/io/kaitai/struct/translators/TypeDetector.scala#L148)).

Should the KSC be capable of resolving this parent graph?
```
        [foo]
         / \
       /     \
   [zero]   [one]
       \     /
         \ /
        [bar]
```
That would mean that `bar._parent` type would not be generic `KaitaiStructType`, but some list of possible parents (let's call it `SomeTypeFrom(UserType('zero'), UserType('one')`). Calling `_parent` on this would iterate the list and evaluate: the only parent of `UserType('zero')` is `UserType('foo')`, the only parent of `UserType('zero')` is `UserType('foo')`. Great, so the type of `bar._parent._parent` is `UserType('foo')`!

No, that looks like a bad idea for such a marginal use case. When someone would need to do that, he can make _bar_ parametric and pass the value from _foo_ in both _zero_ and _one_ types.

I think this issue can be closed then.

**Comment by GreyCat** [comment] 2019-11-24 22:11
I disagree: we clearly *can* make it work, and current limitation of calling `_parent` on KaitaiStrucType should be handled. In implementation, there is definitely nothing preventing us from generating something like

```java
((Foo) (_parent()._parent())).flag()
```

from `_parent._parent.as<foo>.flag`.

**Comment by GreyCat** [comment] 2019-11-24 22:12
Note that @mickdekkers is asking *not* to make `_parent._parent.flag` work, but he's asking for legitimate `_parent._parent.as<foo>.flag`

**Comment by GreyCat** [comment] 2019-12-08 01:35
Looks like this was mostly solved by @generalmimon. Remaining languages:

- [ ] C++
- [ ] Go
- [ ] Nim

These are currently broken in CI and pending restoration of build: C#, Lua, Perl.

Considering this solved.

**Closed by GreyCat** 2019-12-08 01:35 UTC
Labels: bug found

**Comment by jweyrich** [comment] 2020-05-23 07:37
It breaks the covariance in classes that override the method using a different return type. It happens, I guess, because the forwarded declarations don't specify the inheritance - the language doesn't allow that.

```
error: return type of virtual function '_parent' is not covariant with the return type of the function it overrides
      ('microsoft_pe_t::certificate_table_t' is incomplete)
        microsoft_pe_t::certificate_table_t* _parent() const { return m__parent; }
                                             ^
note: forward declaration of 'microsoft_pe_t::certificate_table_t'
    class certificate_table_t;
```

You can reproduce the issue using [microsoft_pe.ksy](https://github.com/kaitai-io/kaitai_struct_formats/blob/master/executable/microsoft_pe.ksy).

**Comment by generalmimon** [comment] 2020-05-23 21:28
@jweyrich Wow, what a fast response 👍! Thanks for the report. I tried to pinpoint the problem by throwing away unnecessary parts of microsoft_pe.ksy and ended up with this:

```yaml
meta:
  id: microsoft_pe
seq:
  - id: pe
    type: pe_header
types:
  pe_header:
    seq:
      - id: data_dirs
        type: optional_header_data_dirs
  optional_header_data_dirs: {}
  foo: {}
  bar: {}
  baz: {}
```

Looking at the generated code, it seems that the problem is that the class `microsoft_pe_t::optional_header_data_dirs_t` is defined **above** the class `microsoft_pe_t::pe_header_t` it uses as the `_parent()` return type:

```cpp
class microsoft_pe_t : public kaitai::kstruct {

public:
    class optional_header_data_dirs_t;
    class pe_header_t;
    // ...
    class optional_header_data_dirs_t : public kaitai::kstruct {

    public:
         // ...
        virtual microsoft_pe_t::pe_header_t* _parent() const { return m__parent; }
    };

    class pe_header_t : public kaitai::kstruct {
        // ...
    }
    // ...
}
```

As you can see, every class uses forward declarations of all its subclasses, but it's not enough for the compiler to know if the `pe_header_t` is a derived class from `kaitai::kstruct`. So it reports that the `microsoft_pe_t::pe_header_t*` is not covariant with`kaitai::kstruct*`. It actually is, but the C++ compiler can't tell.

The solution would be to move `pe_header_t` class declaration above `optional_header_data_dirs_t` that references it. However, this might not be exactly trivial to detect from the KSC, so I will probably revert the change for now.

It'd be tricky to simulate this behavior when you don't have a format that demonstrates it, because the order in which the KSC lists the subclasses seems to be somewhat random. That's the reason why there are three dummy types `foo`, `bar` and `baz`, I'd expect that they won't affect their presence/absence won't affect if the class `pe_header_t` is declared after or before `optional_header_data_dirs_t`, but it does, don't know why.

**Comment by jweyrich** [comment] 2020-05-23 21:48
A person told me to check kaitai yesterday, so I immediately started writing a POC to parse PE files. I frequently contribute to another tool that does that by “hand”. So instead of starting from scratch I found that ksy for PE, which was a good starting point to learn what it can do.
I’ll probably improve that ksy further by adding missing structures.
Luckily or not, I faced a few problems using the kaitai runtime for cpp/stl. I picked tag 0.7 as I figured it would be the latest usable (non broken) version. After putting all together, I decided to give a try with the master branch and ended up here.
Your conclusion seems to be accurate. I did write my conclusion on the previous comment but edited out because I didn’t go thru the testing - it was 4am!
Fast debugging! Thanks for the quick response!

**Comment by generalmimon** [comment] 2020-05-23 21:56
@jweyrich 
> Luckily or not, I faced a few problems using the kaitai runtime for cpp/stl. I picked tag 0.7 as I figured it would be the latest usable (non broken) version. After putting all together, I decided to give a try with the master branch and ended up here.

Sorry to hear that. If there's anything left to fix, please don't hesitate to file a open a [new issue](https://github.com/kaitai-io/kaitai_struct/issues/new), I'll see what I can do.

**Comment by jweyrich** [comment] 2020-05-23 21:59
Sure! Thank you!

I’ll try to contribute as well!

**Comment by Mingun** [comment] 2020-05-24 02:31
I think, that as workaround you can just change return type to `kstruct*` instead of completely removing the method
