### ISSUE TITLE
Nitf.cs doesn't compile

### ISSUE THREAD

**Issue by aarismendi** [kaitai-io/kaitai_struct#1012] opened 2023-02-10 22:49 UTC
I generated Ntif.cs with this command - 

`kaitai-struct-compiler-0.10\bin> .\kaitai-struct-compiler.bat -t csharp "kaitai-struct-compiler-0.10\formats\image\nitf.ksy"`

The resultant Ntif.cs doesn't compile with this error - 

```
(1527) : The type 'Kaitai.Nitf' already contains a definition for 'Header'
(1526) :         private KaitaiStruct m_parent;
(1527) : >>>         public Header Header { get {return _header; } }
```

**Comment by generalmimon** [comment] 2023-02-11 00:55
Yeah, this is an instance of https://github.com/kaitai-io/kaitai_struct/issues/86 and it's (unfortunately) quite common in C#. If you're looking for a workaround, rename the `header` type to something else.

**Comment by generalmimon** [comment] 2023-02-11 00:55
Duplicate of https://github.com/kaitai-io/kaitai_struct/issues/86

**Closed by generalmimon** 2023-02-11 00:55 UTC
Labels: bug found, duplicate
