### ISSUE TITLE
Passing Types as Parameters

### ISSUE THREAD

**Issue by noahcoolboy** [kaitai-io/kaitai_struct#964] opened 2022-04-29 19:53 UTC
Hey there!
I recently started using Kaitai struct and must say it's an excellent piece of software!
However, today I encountered an issue which I couldn't find an answer for.
I searched everywhere in the documentation but didn't find a solution.

Take for example this
```yaml
meta:
  id: example
  endian: le
types:
  kv_pair:
    params:
      - id: key_type
        type: struct
      - id: value_type
        type: struct
    seq:
      - id: key
        type: key_type
      - id: value
        type: value_type
  dictionary:
    seq:
      - id: length
        type: u4
      - id: pairs
        type: kv_pair(u4, str)
seq:
  - id: example
    type: dictionary
```
I would like to create a "kv_pair" type which can get a type passed in its parameters
However, when compiling/running this, you'll get an error saying `unable to find type 'key_type'`
This is probably because KS is taking the type literally and not as an expression
How would this issue be solved?

**Comment by KOLANICH** [comment] 2022-04-30 05:27
Dupe of #135

**Comment by generalmimon** [comment] 2022-06-15 07:40
Duplicate of #135

**Closed by generalmimon** 2022-06-15 07:40 UTC
Labels: enhancement, duplicate
